import React, { useState } from 'react';
import { Play, TrendingUp, Shield, Users, Newspaper, Sparkles, Zap } from 'lucide-react';

export default function LandingPage({ onAnalyze }) {
  const [idea, setIdea] = useState('');

  const submit = (e) => {
    e.preventDefault();
    if (idea.trim()) onAnalyze(idea);
  };

  const features = [
    { icon: <TrendingUp size={16} />, bg: '#EEF2FF', color: '#6366F1', title: 'Google Trends Analysis', desc: 'Track 12-month search interest trajectories and growth velocity.' },
    { icon: <Users size={16} />, bg: '#ECFDF5', color: '#059669', title: 'Competitor Intelligence', desc: 'Map local competitors, ratings, and review sentiment from Google Maps.' },
    { icon: <Newspaper size={16} />, bg: '#FEF3C7', color: '#D97706', title: 'News Sentiment Scoring', desc: 'Aggregate industry news and classify sentiment signals.' },
    { icon: <Shield size={16} />, bg: '#FEF2F2', color: '#DC2626', title: 'Risk & Viability Engine', desc: 'Quantitative scoring across demand, competition, and opportunity.' },
    { icon: <Sparkles size={16} />, bg: '#F0F9FF', color: '#0EA5E9', title: 'AI Consulting Reports', desc: 'McKinsey-grade analysis generated by Gemini AI prompt engine.' },
    { icon: <Zap size={16} />, bg: '#FDF4FF', color: '#A855F7', title: 'Brand Name Validation', desc: 'AI-generated startup names with uniqueness and competition scoring.' },
  ];

  return (
    <div className="page-container">
      <div className="hero">
        <div>
          <div className="hero-badge">
            <Sparkles size={12} />
            AI-Powered Startup Intelligence
          </div>
          <h1>Validate Before You Invest</h1>
          <p className="hero-desc">
            Transform raw startup ideas into data-driven viability reports. Analyze market demand, competitors, trends, and risks using live intelligence from Google and Gemini AI.
          </p>

          <form onSubmit={submit}>
            <div className="hero-input-box">
              <div className="hero-input-row">
                <input
                  type="text"
                  className="input-field"
                  placeholder="Describe your startup idea…"
                  value={idea}
                  onChange={(e) => setIdea(e.target.value)}
                  required
                />
                <button type="submit" className="btn btn-primary btn-lg" style={{ whiteSpace: 'nowrap' }}>
                  <Play size={14} fill="white" /> Analyze
                </button>
              </div>
              <div className="hero-input-hint">
                <span style={{ opacity: 0.6 }}>↵</span> e.g. "Organic pet food delivery in Hyderabad"
              </div>
            </div>
          </form>
        </div>

        <div className="feature-panel">
          {features.map((f, i) => (
            <div key={i} className="feature-item">
              <div className="feature-icon" style={{ background: f.bg, color: f.color }}>
                {f.icon}
              </div>
              <div>
                <h4>{f.title}</h4>
                <p>{f.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
