import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Icon } from '@iconify/react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';
import { Line, Bar } from 'react-chartjs-2';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

const DisclaimerBanner = () => (
  <div className="p-4 rounded-xl bg-indigo-50/40 border border-indigo-100/50 text-indigo-800 text-xs font-semibold leading-relaxed flex items-center gap-3 shadow-sm select-none">
    <Icon icon="lucide:alert-circle" className="text-lg text-indigo-600 flex-shrink-0" />
    <span className="text-left">
      <strong>Transparency Disclaimer:</strong> This feasibility report is generated by AI for preliminary idea validation and market estimation. 
      All financial projections, ratings, and recommendations should be audited by local financial and licensing experts before starting operations.
    </span>
  </div>
);

// ─── HEADER COMPONENT ───────────────────────────────────────────────────────
const ReportHeader = ({ isSaved, onSave, onDownload, onShare, isLoading }) => (
  <header className="sticky top-0 z-50 w-full bg-background/85 backdrop-blur-xl border-b border-border/65 shadow-sm">
    <div className="max-w-[1400px] mx-auto px-6 h-16 flex items-center justify-between">
      <div className="flex items-center gap-4">
        <Link to="/history-dashboard" className="flex items-center justify-center w-8 h-8 rounded-full hover:bg-muted text-foreground transition-colors">
          <Icon icon="lucide:arrow-left" className="text-xl" />
        </Link>
        <div className="h-4 w-px bg-border"></div>
        <div className="flex flex-col">
          <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Decision Engine Report</span>
          <span className="text-sm font-bold text-indigo-600 mt-0.5">BizVision AI</span>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <button 
          onClick={onDownload}
          className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-muted text-sm font-medium transition-colors cursor-pointer"
        >
          <Icon icon="lucide:download" className="text-indigo-600" /> Export PDF/HTML
        </button>
        <button 
          onClick={onShare}
          className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-muted text-sm font-medium transition-colors cursor-pointer"
        >
          <Icon icon="lucide:share-2" className="text-indigo-600" /> Share
        </button>
        <button 
          onClick={onSave}
          disabled={isLoading}
          className={cn(
            "flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-semibold shadow-sm transition-all cursor-pointer",
            isSaved 
              ? "bg-emerald-50 text-emerald-600 border border-emerald-200" 
              : "bg-indigo-600 text-white hover:bg-indigo-700"
          )}
        >
          <Icon icon={isSaved ? "lucide:check" : "lucide:save"} />
          {isLoading ? "Saving..." : isSaved ? "Saved" : "Save to Workspace"}
        </button>
      </div>
    </div>
  </header>
);

// ─── RADIAL GAUGE FOR INVESTMENT READINESS ─────────────────────────────────
const InvestmentReadinessGauge = ({ score, grade, recommendation }) => {
  const strokeDashoffset = 251 - (251 * (score || 50)) / 100;
  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 flex flex-col items-center justify-between min-h-[360px]">
      <h3 className="text-sm font-extrabold text-muted-foreground uppercase tracking-widest mb-4">Investment Readiness</h3>
      
      <div className="relative w-44 h-44 flex items-center justify-center">
        <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="40" fill="none" stroke="#F1F5F9" strokeWidth="8" />
          <circle cx="50" cy="50" r="40" fill="none" stroke="#6366F1" strokeWidth="8"
            strokeDasharray="251" strokeDashoffset={strokeDashoffset} strokeLinecap="round" className="transition-all duration-1000" />
        </svg>
        <div className="absolute flex flex-col items-center">
          <span className="text-4xl font-extrabold text-indigo-600">{score}</span>
          <span className="text-xs font-bold text-muted-foreground uppercase tracking-widest mt-1">Grade {grade}</span>
        </div>
      </div>

      <div className="mt-4 text-center">
        <p className="text-xs text-muted-foreground uppercase font-bold tracking-wider mb-2">VC Strategic Recommendation</p>
        <p className="text-sm leading-relaxed text-foreground font-semibold">
          "{recommendation}"
        </p>
      </div>
    </div>
  );
};

// ─── SCENARIO PROJECTIONS & STARTUP COSTS ──────────────────────────────────
const FinancialSizingSection = ({ revenue, costs }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      {/* Startup Cost Engine */}
      <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
            <Icon icon="lucide:calculator" className="text-xl text-indigo-600" />
          </div>
          <div>
            <h3 className="text-lg font-bold tracking-tight">Startup Cost Breakdown</h3>
            <p className="text-sm text-muted-foreground font-medium">Location-aware capitalization tiers</p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 text-center">
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block mb-1">Minimum Launch</span>
            <span className="text-lg font-extrabold text-slate-700">{costs?.minimum_cost || "₹5,00,000"}</span>
          </div>
          <div className="p-4 bg-indigo-50/50 rounded-xl border border-indigo-100 text-center">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Recommended MVP</span>
            <span className="text-lg font-extrabold text-indigo-700">{costs?.recommended_cost || "₹15,0,000"}</span>
          </div>
          <div className="p-4 bg-cyan-50/50 rounded-xl border border-cyan-100 text-center">
            <span className="text-[10px] font-bold text-cyan-600 uppercase tracking-wider block mb-1">Premium Launch</span>
            <span className="text-lg font-extrabold text-cyan-700">{costs?.premium_launch_cost || "₹25,0,000"}</span>
          </div>
        </div>

        <div className="mt-6 pt-6 border-t border-border/50 space-y-2 text-xs text-muted-foreground leading-relaxed font-medium">
          <p>• Costs encompass local commercial lease deposits, standard fit-outs, early payroll, local licenses, and marketing.</p>
          <p>• Estimated values are resolved based on the target locality pricing indices.</p>
        </div>
      </div>

      {/* Revenue Potential Engine */}
      <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center">
            <Icon icon="lucide:dollar-sign" className="text-xl text-cyan-600" />
          </div>
          <div>
            <h3 className="text-lg font-bold tracking-tight">Revenue Scenario Modeling</h3>
            <p className="text-sm text-muted-foreground font-medium">Conservative, expected, and aggressive cases</p>
          </div>
        </div>

        <div className="space-y-3.5 mb-6">
          <div className="flex justify-between items-center p-3 rounded-lg bg-slate-50 border border-slate-100">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Conservative Scenario (Low Case)</span>
            <span className="text-sm font-extrabold text-slate-700">{revenue?.low_case || "₹2,50,000 /mo"}</span>
          </div>
          <div className="flex justify-between items-center p-3 rounded-lg bg-indigo-50/40 border border-indigo-100">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider">Target Objective (Expected Case)</span>
            <span className="text-sm font-extrabold text-indigo-700">{revenue?.expected_case || "₹8,00,000 /mo"}</span>
          </div>
          <div className="flex justify-between items-center p-3 rounded-lg bg-emerald-50/40 border border-emerald-100">
            <span className="text-xs font-bold text-emerald-600 uppercase tracking-wider">Aggressive Objective (High Case)</span>
            <span className="text-sm font-extrabold text-emerald-700">{revenue?.high_case || "₹20,00,000 /mo"}</span>
          </div>
        </div>

        <div>
          <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider block mb-2">Model Assumptions</span>
          <ul className="space-y-1.5">
            {(revenue?.assumptions || ["Based on local pricing metrics and standard buyer conversions."]).map((asm, i) => (
              <li key={i} className="text-xs text-muted-foreground leading-normal flex gap-2 font-medium">
                <span className="text-emerald-500 font-bold">•</span>
                <span>{asm}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};

// ─── SWOT ANALYSIS QUADRANT ────────────────────────────────────────────────
const SWOTAnalysisSection = ({ swot }) => {
  const quadrants = [
    { title: "Strengths", items: swot?.strengths, icon: "lucide:zap", color: "emerald", bg: "bg-emerald-50/20 border-emerald-100/50 text-emerald-700" },
    { title: "Weaknesses", items: swot?.weaknesses, icon: "lucide:alert-circle", color: "amber", bg: "bg-amber-50/20 border-amber-100/50 text-amber-700" },
    { title: "Opportunities", items: swot?.opportunities, icon: "lucide:lightbulb", color: "indigo", bg: "bg-indigo-50/20 border-indigo-100/50 text-indigo-700" },
    { title: "Threats", items: swot?.threats, icon: "lucide:shield-alert", color: "red", bg: "bg-red-50/20 border-red-100/50 text-red-700" }
  ];

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <h3 className="text-lg font-bold text-foreground mb-6">Strategic SWOT Grid</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {quadrants.map((q, idx) => (
          <div key={idx} className={cn("p-5 rounded-xl border-2 bg-gradient-to-br", q.bg)}>
            <div className="flex items-center gap-2.5 mb-3.5">
              <Icon icon={q.icon} className="text-xl" />
              <h4 className="font-extrabold text-sm uppercase tracking-wider">{q.title}</h4>
            </div>
            <ul className="space-y-2.5">
              {(q.items || ["Insufficient evidence available in search context."]).map((item, i) => (
                <li key={i} className="text-xs leading-relaxed text-foreground flex gap-2 font-normal">
                  <span className="font-bold">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── LAUNCH ROADMAP ROAD TIMELINE ──────────────────────────────────────────
const LaunchRoadmapSection = ({ roadmap }) => {
  const steps = [
    { label: "Day 1 to 30", title: "Operational Sourcing", tasks: roadmap?.first_30_days || ["Identify raw supplier loops", "Publish first waitlist model"] },
    { label: "Day 31 to 60", title: "Pilot Activation", tasks: roadmap?.days_31_to_60 || ["Bootstrap subscription dashboards", "Run trial product soft launch"] },
    { label: "Day 61 to 90", title: "Acquisition scaling", tasks: roadmap?.days_61_to_90 || ["Deploy targeted marketing push", "Stabilize packaging workflows"] }
  ];

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <h3 className="text-lg font-bold text-foreground mb-6">Launch Roadmap & Milestones</h3>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {steps.map((step, idx) => (
          <div key={idx} className="relative p-5 rounded-xl border border-indigo-100 bg-indigo-50/15">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider block mb-1">{step.label}</span>
            <h4 className="text-sm font-extrabold text-foreground mb-3">{step.title}</h4>
            <ul className="space-y-2">
              {step.tasks.map((task, t) => (
                <li key={t} className="text-xs text-muted-foreground leading-normal flex gap-2 font-medium">
                  <span className="text-emerald-500 font-bold">•</span>
                  <span>{task}</span>
                </li>
              ))}
            </ul>
            {idx < steps.length - 1 && (
              <div className="hidden lg:flex absolute -right-3 top-1/2 transform -translate-y-1/2 text-indigo-300 z-10">
                <Icon icon="lucide:arrow-right" className="text-xl" />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── COMPETITORS RATINGS COMPARISON BAR CHART ──────────────────────────────
const CompetitorsRatingsChart = ({ competitors }) => {
  const labels = competitors.map(c => c.name || c.title || 'Competitor');
  const ratings = competitors.map(c => Number(c.rating) || 4.0);

  const data = {
    labels: labels.slice(0, 5),
    datasets: [
      {
        label: 'Competitor Rating',
        data: ratings.slice(0, 5),
        backgroundColor: 'rgba(99, 102, 241, 0.7)',
        borderColor: '#6366F1',
        borderWidth: 2,
        borderRadius: 8,
        barThickness: 32,
      }
    ]
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: '#0F172A',
        padding: 12,
        titleFont: { family: 'Inter', size: 12 },
        bodyFont: { family: 'Inter', size: 13, weight: 'bold' },
        cornerRadius: 6,
      }
    },
    scales: {
      x: { grid: { display: false }, ticks: { font: { family: 'Inter', size: 10 } } },
      y: { min: 0, max: 5, ticks: { stepSize: 1, font: { family: 'Inter', size: 10 } } }
    }
  };

  return (
    <div className="h-64 w-full relative">
      <Bar data={data} options={options} />
    </div>
  );
};

// ─── MAIN REPORT VIEW ───────────────────────────────────────────────────────
const IntelligenceReport = () => {
  const location = useLocation();
  const reportPayload = location.state?.report;

  // Premium offline default fallback data
  const fallbackReport = {
    metadata: {
      idea_text: 'Subscription organic pet food',
      location: 'Hyderabad, India',
      business_type: 'Direct-to-Consumer (D2C)',
      industry: 'Pet Nutrition'
    },
    report: {
      executive_summary: {
        title: "Pawganic Sourcing",
        tagline: "Purity on Every Plate. Certified organic daily meal plans for urban dogs.",
        critical_requirement: "Establishing direct cold-chain logistics loops with poultry farms in Telangana is essential.",
        brand_suggestions: [
          { name: "Pawganic.in", tagline: "Purity on Every Plate.", rationale: "Strong connection to organic formulations and local pets." },
          { name: "NaturaPet.com", tagline: "Natural nutrition for active dogs.", rationale: "Highlights natural organic sourcing and direct home delivery." }
        ]
      },
      market_intelligence: {
        search_velocity: "Moderate search velocity",
        interest_momentum: "Search query interest trends reflect expanding momentum (25% growth) in high-income Telangana residential sectors.",
        forecast: "Strong upward momentum projected over the next 18 months, driven by pet humanization macros."
      },
      competitor_intelligence: {
        market_leader: "Pawsome Bites (Jubilee Hills)",
        top_competitors: [
          { name: "Pawsome Bites", rating: 4.8, reviews: 240, address: "Jubilee Hills, Hyderabad", differentiator: "Established local footprint but lacks custom fresh organic meal formulation plans." },
          { name: "GreenNose Feeders", rating: 4.2, reviews: 84, address: "Gachibowli, Hyderabad", differentiator: "Eco-friendly branding with moderate customer reviews, limited customization." }
        ],
        common_strengths: ["Strong local presence", "Established retail network"],
        common_weaknesses: ["No organic certification", "Poor e-commerce support"],
        unserved_opportunities: ["Certified organic food", "Custom subscription kits"]
      },
      customer_sentiment: {
        love_factors: ["Fresh ingredients", "Fast home delivery", "Tailored portions"],
        pain_points: ["Digestive sensitivities", "Chemical additives", "Inconsistent supply"],
        buying_triggers: ["Vet recommendation", "Healthy coat concerns", "Subscription convenience"],
        market_gap: "Absence of certified local organic pet food suppliers with customized daily delivery options."
      },
      market_saturation: {
        score: 42,
        grade: "A",
        state: "Fragmented / Low Saturation",
        explanation: "Low competitor density in the premium organic niche. Major incumbents focus on mass-market dry kibble via traditional retail."
      },
      revenue_potential: {
        low_case: "₹2,50,000 /mo",
        expected_case: "₹8,00,000 /mo",
        high_case: "₹20,00,000 /mo",
        assumptions: ["Avg spend of ₹2,500/pet", "Conversion rate of 2.5% from waitlist", "Expected 320 subscribers in Month 3"]
      },
      startup_costs: {
        minimum_cost: "₹5,00,000",
        recommended_cost: "₹12,00,000",
        premium_launch_cost: "₹25,0,000"
      },
      location_analysis: {
        location_score: 88,
        grade: "A",
        analysis: "Hyderabad's high-income sectors (Jubilee Hills, Gachibowli) show dense target pet ownership, high purchasing power, and excellent accessibility."
      },
      swot_analysis: {
        strengths: ["First-mover organic brand", "High-margin subscription model"],
        weaknesses: ["Cold-chain supply storage requirements", "High client acquisition cost"],
        opportunities: ["Local vet clinic partnerships", "Expanding to neighboring cities"],
        threats: ["Raw ingredient shelf-life limits", "Price war from commercial brands"]
      },
      risk_analysis: {
        risk_level: "Medium",
        top_risks: ["Supply chain shelf-life consistency", "Ingredient cost inflation"],
        mitigation_strategies: ["Automate delivery logs", "Implement vacuum storage lines", "Advance deposit billing"]
      },
      investment_readiness: {
        investment_score: 82,
        grade: "A",
        recommendation: "Highly viable opportunity. Build local landing page waitlist first to validate customer acquisition cost before capital deployment."
      },
      launch_roadmap: {
        first_30_days: ["Source ingredients from organic suppliers", "Run kitchen tests", "Launch waitlist landing page"],
        days_31_to_60: ["Secure initial clinic partnerships", "Setup subscription billing", "Initiate soft launch (50 orders)"],
        days_61_to_90: ["Gather customer feedback", "Scale social ads budget", "Hire packaging assistants"]
      },
      final_verdict: {
        verdict_status: "🟢 Approved for Pilot",
        financial_viability_outlook: "Premium",
        confidence_level: 85
      }
    },
    competitors: [
      { title: 'Pawsome Bites', rating: 4.8, reviews: 240, address: 'Jubilee Hills, Hyderabad' },
      { title: 'GreenNose Feeders', rating: 4.2, reviews: 84, address: 'Gachibowli, Hyderabad' }
    ],
    trends: [
      { date: 'Jan', value: 45 },
      { date: 'Feb', value: 52 },
      { date: 'Mar', value: 48 },
      { date: 'Apr', value: 61 },
      { date: 'May', value: 59 },
      { date: 'Jun', value: 75 },
      { date: 'Jul', value: 82 },
      { date: 'Aug', value: 80 },
      { date: 'Sep', value: 88 },
      { date: 'Oct', value: 95 },
      { date: 'Nov', value: 91 },
      { date: 'Dec', value: 100 }
    ]
  };

  const report = reportPayload || fallbackReport;
  const isRealReport = !!reportPayload;
  
  // Pivot access nodes
  const data = isRealReport ? report.report : fallbackReport.report;
  const metadata = report.metadata;
  const competitors = report.competitors || [];
  const trends = report.trends || [];

  const [selectedTimeRange, setSelectedTimeRange] = useState('12M');
  const [isSaved, setIsSaved] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const downloadHtmlReport = (reportData) => {
    const { metadata, report: rData, competitors: comps } = reportData;
    const currentData = rData || fallbackReport.report;
    const category = metadata?.idea_text || "Startup Concept";

    const htmlContent = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BizVision AI - VC Decision Engine Report</title>
    <style>
      body {
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
        line-height: 1.6;
        color: #0F172A;
        background-color: #FAFBFD;
        margin: 0;
        padding: 40px 20px;
      }
      .container {
        max-width: 900px;
        margin: 0 auto;
        background: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 24px;
        padding: 40px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.02);
      }
      .header {
        border-bottom: 2px solid #F1F5F9;
        padding-bottom: 30px;
        margin-bottom: 30px;
      }
      .title {
        font-size: 28px;
        font-weight: 800;
        color: #1E1B4B;
        margin: 0 0 10px 0;
      }
      .meta {
        font-size: 14px;
        color: #64748B;
        font-weight: 600;
      }
      .score-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 15px;
        margin-bottom: 30px;
      }
      .score-card {
        background: #F8FAFC;
        border: 1px solid #E2E8F0;
        border-radius: 12px;
        padding: 15px;
        text-align: center;
      }
      .score-label {
        font-size: 10px;
        font-weight: 700;
        color: #64748B;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        margin-bottom: 5px;
      }
      .score-value {
        font-size: 24px;
        font-weight: 800;
        color: #4F46E5;
      }
      .section {
        margin-bottom: 35px;
      }
      .section-title {
        font-size: 18px;
        font-weight: 700;
        color: #1E1B4B;
        border-left: 4px solid #4F46E5;
        padding-left: 12px;
        margin-bottom: 15px;
      }
      .card {
        background: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 16px;
        padding: 20px;
        margin-bottom: 15px;
      }
      .list-item {
        margin-bottom: 8px;
        font-size: 14px;
      }
      .bullet {
        color: #10B981;
        font-weight: bold;
        margin-right: 8px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1 class="title">"${currentData.executive_summary?.title || category}"</h1>
        <div class="meta">
          📍 Location: ${metadata?.location || 'Global'} &nbsp;|&nbsp; 
          💼 Industry: ${metadata?.industry || 'General'}
        </div>
      </div>

      <div class="score-grid">
        <div class="score-card">
          <div class="score-label">Investment readiness</div>
          <div class="score-value">${currentData.investment_readiness?.investment_score || 50}</div>
        </div>
        <div class="score-card">
          <div class="score-label">Market Saturation</div>
          <div class="score-value">${currentData.market_saturation?.score || 50}</div>
        </div>
        <div class="score-card">
          <div class="score-label">Location score</div>
          <div class="score-value">${currentData.location_analysis?.location_score || 50}</div>
        </div>
        <div class="score-card">
          <div class="score-label">Confidence level</div>
          <div class="score-value">${currentData.final_verdict?.confidence_level || 85}%</div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">Executive Summary</div>
        <div class="card">
          <p><strong>Tagline:</strong> "${currentData.executive_summary?.tagline}"</p>
          <p><strong>Critical dependency:</strong> ${currentData.executive_summary?.critical_requirement}</p>
        </div>
      </div>

      <div class="section">
        <div class="section-title">Competitor Saturation</div>
        <div class="card">
          <p><strong>Market leader:</strong> ${currentData.competitor_intelligence?.market_leader}</p>
          <h4 style="margin: 15px 0 10px 0;">Identified Competitors:</h4>
          ${(currentData.competitor_intelligence?.top_competitors || comps || []).map(c => `
            <div style="margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid #F1F5F9;">
              <strong>${c.name || c.title}</strong> (${c.rating || 4.0}★)
              <p style="margin: 5px 0; font-size: 13px; color: #64748B;">${c.differentiator || "Local provider servicing traditional markets."}</p>
            </div>
          `).join('')}
        </div>
      </div>

      <div class="section">
        <div class="section-title">Action Plan Roadmap</div>
        <div class="card">
          <p><strong>Month 1 (Days 1–30):</strong></p>
          ${(currentData.launch_roadmap?.first_30_days || []).map(t => `<div class="list-item"><span class="bullet">●</span> ${t}</div>`).join('')}
          <p style="margin-top: 15px;"><strong>Month 2 (Days 31–60):</strong></p>
          ${(currentData.launch_roadmap?.days_31_to_60 || []).map(t => `<div class="list-item"><span class="bullet">●</span> ${t}</div>`).join('')}
          <p style="margin-top: 15px;"><strong>Month 3 (Days 61–90):</strong></p>
          ${(currentData.launch_roadmap?.days_61_to_90 || []).map(t => `<div class="list-item"><span class="bullet">●</span> ${t}</div>`).join('')}
        </div>
      </div>
    </div>
  </body>
  </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const fileName = (metadata?.idea_text || "Report")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    link.download = `bizvision-ai-${fileName || 'report'}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = useCallback(() => {
    window.print();
    downloadHtmlReport(report);
  }, [report]);

  const handleShare = useCallback(() => {
    const url = window.location.href;
    navigator.clipboard.writeText(url).then(() => {
      alert('Report link copied to clipboard!');
    });
  }, []);

  const handleSaveToWorkspace = useCallback(() => {
    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      setIsSaved(prev => !prev);
    }, 800);
  }, []);

  const handleTimeRangeChange = useCallback((range) => {
    setSelectedTimeRange(range);
  }, []);

  const handleGenerateBusinessPlan = useCallback(() => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      alert('AI Business Plan generation started! Check back shortly.');
    }, 2000);
  }, []);

  const defaultLabels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const defaultPoints = [45, 52, 48, 61, 59, 75, 82, 80, 88, 95, 91, 100];
  const baseLabels = trends && trends.length > 0 ? trends.map(t => t.date) : defaultLabels;
  const basePoints = trends && trends.length > 0 ? trends.map(t => {
    if (t.values && t.values.length > 0) {
      const firstVal = t.values[0];
      const val = Number(firstVal.extracted_value !== undefined ? firstVal.extracted_value : firstVal.value);
      if (!isNaN(val)) return val;
    }
    if (t.value !== undefined && t.value !== null) {
      const val = Number(t.value);
      if (!isNaN(val)) return val;
    }
    return 0;
  }) : defaultPoints;

  const dataLine = {
    labels: baseLabels,
    datasets: [
      {
        label: 'Interest velocity',
        data: basePoints,
        borderColor: '#6366F1',
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        borderWidth: 3,
        pointBackgroundColor: '#FFFFFF',
        pointBorderColor: '#6366F1',
        pointBorderWidth: 2,
        tension: 0.35,
        fill: true,
      }
    ]
  };

  return (
    <div className="min-h-screen w-full bg-slate-50/50 flex flex-col relative font-sans text-slate-800">
      <ReportHeader 
        isSaved={isSaved}
        onSave={handleSaveToWorkspace}
        onDownload={handleDownloadPDF}
        onShare={handleShare}
        isLoading={isLoading}
      />

      <main className="flex-1 w-full max-w-[1400px] mx-auto px-6 py-8 space-y-8 pb-32">
        <DisclaimerBanner />

        {/* Venture Statement Callout */}
        <div className="p-8 rounded-[2rem] bg-white border border-slate-200/60 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-indigo-50 text-indigo-600 uppercase tracking-wider">
              <Icon icon="lucide:sparkles" /> Enterprise intelligence
            </span>
            <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-900">
              "{metadata?.idea_text || 'Startup Feasibility'}"
            </h1>
            <div className="flex items-center gap-4 text-xs font-semibold text-slate-500">
              <span className="flex items-center gap-1"><Icon icon="lucide:map-pin" className="text-sm text-indigo-600" /> {metadata?.location || 'Global'}</span>
              <span className="flex items-center gap-1"><Icon icon="lucide:briefcase" className="text-sm text-indigo-600" /> {metadata?.business_type || 'General'}</span>
            </div>
          </div>
          <div className="flex items-center gap-2 text-xs font-bold bg-emerald-50 text-emerald-600 border border-emerald-200 px-3.5 py-2 rounded-xl self-start md:self-center">
            <Icon icon="lucide:check-circle-2" className="text-sm text-emerald-500" /> VC Validated Pipeline
          </div>
        </div>

        {/* Executive summary + Score gauge */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Executive Summary */}
          <div className="bg-card bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 lg:col-span-2 flex flex-col justify-between">
            <div className="space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
                  <Icon icon="lucide:file-text" className="text-xl text-indigo-600" />
                </div>
                <div>
                  <h2 className="text-xl font-extrabold tracking-tight">Executive Intelligence</h2>
                  <p className="text-xs text-slate-400 font-bold uppercase tracking-wider mt-0.5">Corporate feasibility brief</p>
                </div>
              </div>
              <h3 className="text-xl font-extrabold text-indigo-900">"{data.executive_summary?.title}"</h3>
              <p className="text-sm leading-relaxed text-slate-600 font-medium">"{data.executive_summary?.tagline}"</p>
              <div className="p-4 rounded-xl bg-indigo-50/40 border border-indigo-100/50">
                <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1.5">Critical launch requirement</span>
                <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.executive_summary?.critical_requirement}</p>
              </div>
            </div>

            {/* Brand Naming Suggestions */}
            <div className="mt-8 pt-6 border-t border-slate-100 space-y-4">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block">AI Brand recommendations</span>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {(data.executive_summary?.brand_suggestions || []).map((brand, bIdx) => (
                  <div key={bIdx} className="p-4 bg-slate-50 rounded-xl border border-slate-100">
                    <span className="text-sm font-extrabold text-slate-800">{brand.name}</span>
                    <span className="text-[10px] italic text-indigo-600 block font-semibold mt-0.5">"{brand.tagline}"</span>
                    <p className="text-xs text-slate-500 mt-2 font-medium">{brand.rationale}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Investment readiness score gauge */}
          <InvestmentReadinessGauge 
            score={data.investment_readiness?.investment_score} 
            grade={data.investment_readiness?.grade} 
            recommendation={data.investment_readiness?.recommendation} 
          />
        </div>

        {/* 4 KPIs grid stats */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="p-6 bg-white rounded-2xl border border-slate-200/60 shadow-sm">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2">Market Saturation</span>
            <span className="text-2xl font-extrabold text-indigo-600 block">{data.market_saturation?.score} /100</span>
            <span className="text-xs font-bold text-indigo-500 block mt-1">{data.market_saturation?.state} ({data.market_saturation?.grade})</span>
          </div>
          <div className="p-6 bg-white rounded-2xl border border-slate-200/60 shadow-sm">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2">Location attractiveness</span>
            <span className="text-2xl font-extrabold text-indigo-600 block">{data.location_analysis?.location_score} /100</span>
            <span className="text-xs font-bold text-indigo-500 block mt-1">Grade {data.location_analysis?.grade}</span>
          </div>
          <div className="p-6 bg-white rounded-2xl border border-slate-200/60 shadow-sm">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2">Risk profile</span>
            <span className="text-2xl font-extrabold text-indigo-600 block">{data.risk_analysis?.risk_level}</span>
            <span className="text-xs font-bold text-indigo-500 block mt-1">Mitigations modeled</span>
          </div>
          <div className="p-6 bg-white rounded-2xl border border-slate-200/60 shadow-sm">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2">Confidence metric</span>
            <span className="text-2xl font-extrabold text-indigo-600 block">{data.final_verdict?.confidence_level}%</span>
            <span className="text-xs font-bold text-indigo-500 block mt-1">Calculated via data consistency</span>
          </div>
        </div>

        {/* Market Saturation text */}
        <div className="bg-card bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-2">Market Saturation Justification</span>
          <p className="text-sm leading-relaxed text-slate-600 font-medium">{data.market_saturation?.explanation}</p>
        </div>

        {/* Market intelligence trend chart + interpretations */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 bg-white rounded-[2rem] p-8 border border-slate-200/60 shadow-sm">
            <div className="flex justify-between items-center mb-6">
              <span className="text-sm font-extrabold text-slate-800">Local Search velocity (Past 12 Months)</span>
              <span className="text-xs font-bold bg-indigo-50 text-indigo-600 px-2.5 py-1 rounded-lg border border-indigo-100">{data.market_intelligence?.search_velocity}</span>
            </div>
            <div className="h-64 w-full relative">
              <Line data={dataLine} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} />
            </div>
          </div>

          <div className="bg-white rounded-[2rem] p-8 border border-slate-200/60 shadow-sm flex flex-col justify-between">
            <div className="space-y-4">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-1">Local demand trajectory</span>
              <p className="text-sm text-slate-700 leading-relaxed font-semibold">"{data.market_intelligence?.interest_momentum}"</p>
            </div>
            <div className="pt-6 border-t border-slate-100">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1.5">18-Month Outlook forecast</span>
              <p className="text-xs text-indigo-600 leading-relaxed font-bold">"{data.market_intelligence?.forecast}"</p>
            </div>
          </div>
        </div>

        {/* Competitor list + Competitor bar chart */}
        <div className="bg-card bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
          <div className="flex items-center gap-3 mb-8">
            <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center">
              <Icon icon="lucide:crosshair" className="text-xl text-amber-600" />
            </div>
            <div>
              <h3 className="text-lg font-bold tracking-tight">Competitor Intelligence</h3>
              <p className="text-sm text-muted-foreground font-medium">Incumbents & differentiator maps</p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
            <div className="lg:col-span-2 space-y-4">
              <div className="p-3 bg-slate-50 border border-slate-100 rounded-lg flex items-center gap-2">
                <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Identified Market Leader:</span>
                <span className="text-xs font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 px-2 py-0.5 rounded">{data.competitor_intelligence?.market_leader}</span>
              </div>
              <div className="space-y-3">
                {(data.competitor_intelligence?.top_competitors || competitors).slice(0, 3).map((comp, idx) => (
                  <div key={idx} className="p-4 bg-slate-50/50 rounded-xl border border-slate-100 flex items-start gap-4">
                    <div className="w-10 h-10 bg-indigo-50 text-indigo-600 font-bold flex items-center justify-center rounded-lg flex-shrink-0">
                      {(comp.name || comp.title || 'CO').slice(0, 2).toUpperCase()}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-bold text-slate-800">{comp.name || comp.title}</span>
                        <span className="text-xs font-bold text-amber-500">★ {comp.rating || "4.0"} ({comp.reviews || "0"} reviews)</span>
                      </div>
                      <p className="text-xs text-slate-400 mt-1 font-semibold">{comp.address}</p>
                      <p className="text-xs text-slate-600 mt-2 font-medium"><strong>Differentiation Hook:</strong> {comp.differentiator || "Local provider servicing traditional markets."}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-slate-50/40 rounded-2xl p-6 border border-slate-100">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block mb-4">Competitor ratings comparison</span>
              <CompetitorsRatingsChart competitors={data.competitor_intelligence?.top_competitors || competitors} />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-6 border-t border-slate-100">
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Common strengths</span>
              <ul className="space-y-1">
                {(data.competitor_intelligence?.common_strengths || []).map((s, i) => (
                  <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-medium">
                    <span className="text-emerald-500">•</span> {s}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Common weaknesses</span>
              <ul className="space-y-1">
                {(data.competitor_intelligence?.common_weaknesses || []).map((w, i) => (
                  <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-medium">
                    <span className="text-red-500">•</span> {w}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Unserved opportunities</span>
              <ul className="space-y-1">
                {(data.competitor_intelligence?.unserved_opportunities || []).map((o, i) => (
                  <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-medium">
                    <span className="text-indigo-500">•</span> {o}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Customer sentiment analysis */}
        <div className="bg-card bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
              <Icon icon="lucide:smile" className="text-xl text-indigo-600" />
            </div>
            <div>
              <h3 className="text-lg font-bold tracking-tight">Customer Sentiment Miner</h3>
              <p className="text-sm text-muted-foreground font-medium">Customer expectations & purchase signals</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
            <div className="p-5 bg-emerald-50/20 border border-emerald-100 rounded-xl">
              <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider block mb-2">Love factors</span>
              <ul className="space-y-2">
                {(data.customer_sentiment?.love_factors || []).map((item, i) => (
                  <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-medium">
                    <span className="text-emerald-500 font-bold">•</span> {item}
                  </li>
                ))}
              </ul>
            </div>
            <div className="p-5 bg-red-50/20 border border-red-100 rounded-xl">
              <span className="text-[10px] font-bold text-red-600 uppercase tracking-wider block mb-2">Customer frustrations</span>
              <ul className="space-y-2">
                {(data.customer_sentiment?.pain_points || []).map((item, i) => (
                  <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-medium">
                    <span className="text-red-500 font-bold">•</span> {item}
                  </li>
                ))}
              </ul>
            </div>
            <div className="p-5 bg-indigo-50/20 border border-indigo-100 rounded-xl">
              <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-2">Buying triggers</span>
              <ul className="space-y-2">
                {(data.customer_sentiment?.buying_triggers || []).map((item, i) => (
                  <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-medium">
                    <span className="text-indigo-500 font-bold">•</span> {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Identified Local Market Gap</span>
            <p className="text-xs text-slate-700 leading-relaxed font-semibold">"{data.customer_sentiment?.market_gap}"</p>
          </div>
        </div>

        {/* Costs and scenario matrix */}
        <FinancialSizingSection revenue={data.revenue_potential} costs={data.startup_costs} />

        {/* Location analysis info */}
        <div className="bg-card bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0_0,0.04)] border border-border/50">
          <div className="flex items-center gap-3 mb-4">
            <Icon icon="lucide:map" className="text-xl text-indigo-600" />
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Geographical Locality assessment</span>
          </div>
          <p className="text-sm text-slate-700 leading-relaxed font-semibold">"{data.location_analysis?.analysis}"</p>
        </div>

        {/* SWOT Analysis */}
        <SWOTAnalysisSection swot={data.swot_analysis} />

        {/* Risk Mitigation */}
        <div className="bg-card bg-white rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-red-50 flex items-center justify-center">
              <Icon icon="lucide:shield-alert" className="text-xl text-red-600" />
            </div>
            <div>
              <h3 className="text-lg font-bold tracking-tight">Risk Engine Assessment</h3>
              <p className="text-sm text-muted-foreground font-medium">Identified threats & tactical mitigation</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2.5">Top Category Risks</span>
              <ul className="space-y-2">
                {(data.risk_analysis?.top_risks || []).map((risk, i) => (
                  <li key={i} className="text-xs text-slate-700 leading-relaxed flex gap-2 font-medium">
                    <span className="text-red-500 font-bold">•</span> {risk}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2.5">Mitigation Strategies</span>
              <ul className="space-y-2">
                {(data.risk_analysis?.mitigation_strategies || []).map((strat, i) => (
                  <li key={i} className="text-xs text-slate-700 leading-relaxed flex gap-2 font-medium">
                    <span className="text-emerald-500 font-bold">•</span> {strat}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Timeline roadmap milestones */}
        <LaunchRoadmapSection roadmap={data.launch_roadmap} />

        {/* Final verdict premium CTA */}
        <FinalVerdict 
          scores={{ viability: data.investment_readiness?.investment_score }}
          analysis={{ final_recommendation: JSON.stringify({ next_step: data.investment_readiness?.recommendation, status: data.final_verdict?.verdict_status }) }}
          onGenerate={handleGenerateBusinessPlan}
          onSave={handleSaveToWorkspace}
          isLoading={isGenerating}
          metadata={metadata}
        />
      </main>
    </div>
  );
};

// ─── FINAL VERDICT PANEL ───────────────────────────────────────────────────
const FinalVerdict = ({ scores, analysis, onGenerate, onSave, isLoading, metadata }) => {
  const viability = scores?.viability || 50;
  const statusColor = viability >= 75 ? "from-emerald-600 to-emerald-700" : 
                      viability >= 45 ? "from-amber-600 to-amber-700" : 
                      "from-red-600 to-red-700";
  
  const parsed = parseJSON(analysis?.final_recommendation, {});
  const nextStep = parsed.next_step || "Validate economic parameters before launch.";
  const statusBadge = parsed.status || "Approved for Pilot";

  return (
    <div className={`bg-gradient-to-r ${statusColor} rounded-[2rem] p-8 md:p-12 shadow-2xl relative overflow-hidden flex flex-col gap-8 text-white`}>
      <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full blur-[100px] pointer-events-none -translate-y-1/2 translate-x-1/3"></div>
      <div className="relative z-10">
        <p className="text-xs font-bold uppercase tracking-widest text-white/80 mb-6">Investment Verdict Summary</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">VC Confidence</p>
            <p className="text-3xl font-extrabold">{viability}%</p>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Status Verdict</p>
            <p className="text-lg font-bold">{statusBadge}</p>
          </div>
        </div>
        <div className="pt-6 border-t border-white/20">
          <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Recommended Next Action Step</p>
          <p className="text-sm font-semibold text-white leading-relaxed">"{nextStep}"</p>
        </div>
      </div>
      <div className="relative z-10 pt-4 flex gap-4">
        <button 
          onClick={onGenerate}
          disabled={isLoading}
          className="bg-white text-indigo-600 hover:bg-indigo-50 px-6 py-3 rounded-lg font-bold shadow-lg transition-all flex items-center justify-center gap-2 disabled:opacity-70 cursor-pointer"
        >
          <Icon icon={isLoading ? "lucide:loader-2" : "lucide:rocket"} className={isLoading && "animate-spin"} />
          {isLoading ? "Generating..." : "Generate Full Business Plan"}
        </button>
        <button 
          onClick={onSave}
          className="bg-white/10 hover:bg-white/20 text-white border border-white/30 px-6 py-3 rounded-lg font-bold transition-all flex items-center justify-center gap-2 cursor-pointer"
        >
          <Icon icon="lucide:bookmark" /> Bookmark Report
        </button>
      </div>
    </div>
  );
};

const parseJSON = (raw, defaultValue) => {
  if (!raw) return defaultValue;
  try {
    let clean = raw.trim();
    if (clean.startsWith("```")) {
      clean = clean.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
    }
    return JSON.parse(clean);
  } catch (e) {
    return defaultValue;
  }
};

export default IntelligenceReport;
