import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Icon } from '@iconify/react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';
import { Line } from 'react-chartjs-2';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

const formatBusinessTitle = (ideaText) => {
  if (!ideaText) return "Startup Feasibility Report";
  let text = ideaText.trim();
  
  // Strip common startup sentence prefixes
  text = text.replace(/^(i\s+)?want\s+to\s+(start|open|create|build|launch|run|make|have|do)\s+(a\s+)?/i, "");
  // Strip leading and trailing quotes or periods
  text = text.replace(/^["']|["']$/g, "").replace(/\.+$/, "").trim();
  
  // Format specific keywords into professional phrases
  text = text.replace(/\bpure\s+veg\b/i, "Pure Vegetarian");
  text = text.replace(/\bveg\b/i, "Vegetarian");
  text = text.replace(/\bhotel\b/i, "Hotel");
  text = text.replace(/\brestaurant\b/i, "Restaurant");
  text = text.replace(/\bcafe\b/i, "Cafe");
  text = text.replace(/\bshop\b/i, "Store");
  
  // Capitalize each word (Title Case)
  text = text.split(/\s+/).map(word => {
    if (!word) return "";
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  }).join(" ");
  
  if (!text.endsWith("Feasibility Report") && !text.endsWith("Startup Feasibility Report")) {
    return `${text} Startup Feasibility Report`;
  }
  return text;
};

const normalizeLocation = (loc, ideaText) => {
  const locationStr = (loc || "").trim();
  const text = (ideaText || "").toLowerCase();
  const isPhysical = /hotel|veg|restaurant|shop|cafe|store|salon|bakery|dhabha|spa|boutique|delivery|gym|clinic|dentist|laundry/i.test(text);
  if (isPhysical) {
    if (!locationStr || locationStr.toLowerCase() === "global / online" || locationStr.toLowerCase() === "global" || locationStr.toLowerCase() === "online") {
      return "Local Urban Market (India)";
    }
  }
  return locationStr || "Local Urban Market (India)";
};

const DisclaimerBanner = () => (
  <div className="p-4 rounded-xl bg-indigo-50/40 border border-indigo-100 text-indigo-800 text-xs font-semibold leading-relaxed flex items-center gap-3 shadow-sm select-none">
    <Icon icon="lucide:alert-circle" className="text-lg text-indigo-600 flex-shrink-0" />
    <span className="text-left">
      <strong>Transparency Disclaimer:</strong> This feasibility report is generated by AI for preliminary idea validation and market estimation. 
      All financial projections, ratings, and recommendations should be audited by local financial and licensing experts before starting operations.
    </span>
  </div>
);

// ─── HELPER FUNCTIONS FOR CLEAN JSON PARSING & BUSINESS CATEGORIES ──────────
const parseJSON = (raw, defaultValue) => {
  if (!raw) return defaultValue;
  try {
    let clean = raw.trim();
    if (clean.startsWith("```")) {
      clean = clean.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
    }
    return JSON.parse(clean);
  } catch (e) {
    return defaultValue;
  }
};

const getBusinessCategory = (ideaText) => {
  const text = (ideaText || "").toLowerCase();
  if (/candle|soap|perfume|gift|craft|furniture|home decor|clothing|fashion|apparel|jewelry|bag|shoes|book|toy|hardware/i.test(text)) {
    return { type: "physical_product", label: "Consumer Packaged Goods" };
  }
  if (/hotel|veg|restaurant|shop|cafe|store|salon|bakery|dhabha|spa|boutique|delivery|gym|clinic|dentist|laundry/i.test(text)) {
    return { type: "local_service", label: "Local Brick & Mortar" };
  }
  if (/saas|software|crm|billing|api|platform|dashboard|cloud|database|erp|analytics|ai tool/i.test(text)) {
    return { type: "saas", label: "Software as a Service (SaaS)" };
  }
  if (/app|mobile|game|delivery app|marketplace|dating|social network|e-commerce/i.test(text)) {
    return { type: "digital_platform", label: "Digital Platform" };
  }
  return { type: "general", label: "Business Services" };
};

// ─── DYNAMIC COGNITIVE GENERATORS FOR RESILIENT OFF-LINE FALLBACKS ──────────
const generateFallbackSWOT = (ideaText, category) => {
  const isSaaS = category.type === "saas" || category.type === "digital_platform";
  const isLocal = category.type === "local_service";
  
  if (isSaaS) {
    return {
      strengths: [
        "High gross margins and recurring subscription revenue potential.",
        "Global market reach with low product distribution and replication friction."
      ],
      weaknesses: [
        "High developer resource cost and product onboarding friction.",
        "Dependence on technical infrastructure and cloud provider pricing."
      ],
      opportunities: [
        "B2B corporate subscription licensing and white-label packages.",
        "Integration into existing platform ecosystems via open API endpoints."
      ],
      threats: [
        "Low barrier to entry for clone products and software duplication.",
        "Rapidly changing technology stacks and security compliance costs."
      ]
    };
  } else if (isLocal) {
    return {
      strengths: [
        "Direct customer relationships and immediate cash flow collection.",
        "Local geographic presence helps build community trust and loyalty."
      ],
      weaknesses: [
        "High physical location overhead and lease commitments.",
        "Operational scalability capped by geographical service footprint."
      ],
      opportunities: [
        "Cross-promotional partnerships with nearby complementary merchants.",
        "Online pre-ordering and localized home-delivery services."
      ],
      threats: [
        "Local municipal regulation or zoning restriction adjustments.",
        "Incumbent local price wars and aggressive advertising campaigns."
      ]
    };
  } else {
    return {
      strengths: [
        "Strong emotional appeal and tangible consumer touchpoints.",
        "Low initial manufacturing complexity for starting production batches."
      ],
      weaknesses: [
        "Inventory storage overhead and supply chain shipping delays.",
        "Limited brand awareness compared to mass-market manufacturers."
      ],
      opportunities: [
        "Customized corporate gifting sets and seasonal festival boxes.",
        "E-commerce marketplace expansion on Amazon, Shopify, or Etsy."
      ],
      threats: [
        "Volatile raw material costs and packaging supply shortages.",
        "Low-cost mass-manufactured imports undercutting price points."
      ]
    };
  }
};

const generateFallbackRoadmap = (ideaText, category) => {
  const isSaaS = category.type === "saas" || category.type === "digital_platform";
  const isLocal = category.type === "local_service";
  
  if (isSaaS) {
    return [
      { phase: "Week 1–2", title: "MVP Validation", tasks: ["Conduct target user interviews", "Launch landing page with email waitlist signups"] },
      { phase: "Week 3–4", title: "Feature Refinement", tasks: ["Build core prototype dashboard", "Setup billing integration and auth system"] },
      { phase: "Month 2", title: "Pilot Launch", tasks: ["Deploy beta build to early waitlist users", "Gather bug reports and user feedback"] },
      { phase: "Month 3", title: "User Acquisition", tasks: ["Launch targeted search ads", "Roll out organic content marketing campaign"] }
    ];
  } else if (isLocal) {
    return [
      { phase: "Week 1–2", title: "Menu Finalization", tasks: ["Draft core menu options and price tiers", "Analyze local foot-traffic and competitor density"] },
      { phase: "Week 3–4", title: "Supplier & Permits", tasks: ["Complete supplier sourcing for ingredients", "Submit FSSAI registration & municipal health permits"] },
      { phase: "Month 2", title: "Trial Kitchen Setup", tasks: ["Set up trial kitchen layout and cooking operations", "Run soft launch tastes for friends and local critics"] },
      { phase: "Month 3", title: "Grand Launch", tasks: ["Open physical doors for dine-in operations", "Deploy local delivery partner integrations"] }
    ];
  } else {
    return [
      { phase: "Week 1–2", title: "Product Testing", tasks: ["Conduct formulation and durability tests", "Gather feedback from friends and family trials"] },
      { phase: "Week 3–4", title: "Small Batch Launch", tasks: ["Order raw materials for first 100 units", "Set up e-commerce store page on Shopify/Etsy"] },
      { phase: "Month 2", title: "Local Sales", tasks: ["Pitch products to local boutique retail stores", "Host pop-up stands at weekend flea markets"] },
      { phase: "Month 3", title: "Marketplace Onboarding", tasks: ["Apply for Amazon Seller Central registry", "Scale batch size and run social media ads"] }
    ];
  }
};

const generateFallbackVerdictReasons = (scores) => {
  const viability = scores?.viability || 50;
  const demand = scores?.demand || 50;
  const comp = scores?.competition || 50;
  
  const reasons = [];
  if (demand >= 75) {
    reasons.push("Robust search query density and active consumer query velocity reflect strong market interest.");
  } else if (demand >= 45) {
    reasons.push("Steady search query velocity indicates a stable but niche market demand.");
  } else {
    reasons.push("Conservative search volume suggests a niche segment requiring targeted user education.");
  }
  
  if (comp < 50) {
    reasons.push("Low competitor density and positive reviews suggest a high entry capability and clear market gaps.");
  } else if (comp < 70) {
    reasons.push("Moderate competitive saturation requires clear differentiator positioning to win market share.");
  } else {
    reasons.push("Intense competitive density requires building a high-barrier operational or technology moat.");
  }
  
  if (viability >= 80) {
    reasons.push("Excellent unit economics and high scalability potential support a rapid capital payback period.");
  } else if (viability >= 60) {
    reasons.push("Feasibility metrics support pilot activities, requiring validation of customer acquisition costs.");
  } else {
    reasons.push("Significant market entry barriers or high operating costs require adjustments to the business model.");
  }
  
  return reasons;
};

const generateDynamicFallbackInsights = (metadata, scores) => {
  const category = getBusinessCategory(metadata?.idea_text);
  const location = metadata?.location || "the local area";
  const keywords = metadata?.keywords ? metadata.keywords.split(',')[0].trim() : "this business";
  
  const demand = scores?.demand || 50;
  const competition = scores?.competition || 50;
  const viability = scores?.viability || 50;

  const demandText = demand >= 75 
    ? `Demand Insight: Extremely robust search volume for "${keywords}" indicates high consumer awareness.`
    : demand >= 45 
      ? `Demand Insight: Consistent interest patterns highlight a stable, predictable customer base.`
      : `Demand Insight: Niche target audience requires focused educational marketing to drive adoption.`;

  const customerText = category.type === "saas" || category.type === "digital_platform"
    ? "Customer Insight: Target users prioritize seamless onboarding, intuitive UI, and immediate value."
    : category.type === "local_service"
      ? `Customer Insight: Local consumers in ${location} value premium customer service, reliability, and convenience.`
      : "Customer Insight: Buyers look for unique product designs, organic materials, and transparent sourcing.";

  const revenueText = viability >= 75
    ? "Revenue Insight: High operational margins provide strong pricing power and rapid path to profitability."
    : "Revenue Insight: Subscription tiers or bundled pricing can help optimize early-stage customer lifetime value.";

  const competitionText = competition >= 70
    ? "Competition Insight: Established incumbents exist; focus on a specific niche or superior pricing to break in."
    : competition >= 40
      ? `Competition Insight: Saturation is moderate in ${location}, leaving room for a well-differentiated brand.`
      : `Competition Insight: Highly fragmented landscape offers a great opportunity to capture first-mover advantage.`;

  const growthText = category.type === "saas" || category.type === "digital_platform"
    ? "Growth Insight: Scalable code infrastructure allows geographic expansion with low marginal costs."
    : `Growth Insight: Expansion to neighboring areas or partnering with local venues provides a clear path to scale.`;

  return [demandText, customerText, revenueText, competitionText, growthText];
};

const generateDynamicKeyInsight = (metadata, scores) => {
  const category = getBusinessCategory(metadata?.idea_text);
  const location = metadata?.location || "your target location";
  const industry = metadata?.industry || category.label;
  const keywords = metadata?.keywords ? metadata.keywords.split(',')[0].trim() : "this concept";
  const demand = scores?.demand || 50;
  const viability = scores?.viability || 50;
  const competition = scores?.competition || 50;

  let demandPhrase = "";
  if (demand >= 75) {
    demandPhrase = `Excellent query interest and rising volume for "${keywords}" indicates a strong consumer pull in the ${industry} space.`;
  } else if (demand >= 45) {
    demandPhrase = `Steady, moderate search volumes suggest a stable and reliable demand pipeline for "${keywords}" in the local area.`;
  } else {
    demandPhrase = `Niche search demand indicates a highly targeted or emerging consumer base for "${keywords}", requiring focused buyer education.`;
  }

  let opportunityPhrase = "";
  if (viability >= 75) {
    if (category.type === "saas" || category.type === "digital_platform") {
      opportunityPhrase = `This presents a highly scalable digital opportunity with strong operational margins and low reproduction costs.`;
    } else if (category.type === "local_service") {
      opportunityPhrase = `This presents a solid brick-and-mortar opportunity to establish a premium local presence and capture direct cash flow.`;
    } else {
      opportunityPhrase = `This presents a premium product opportunity with excellent unit economics and strong branding potential.`;
    }
  } else if (viability >= 50) {
    opportunityPhrase = `Launching a pilot version in ${location} is highly feasible to test unit economics and gather real customer feedback.`;
  } else {
    opportunityPhrase = `Developing a low-capital prototype is recommended to validate consumer interest before scaling operations.`;
  }

  let tacticalPhrase = "";
  if (competition >= 70) {
    tacticalPhrase = `Due to high local competition, success hinges on building a unique brand moat and offering superior customer service or pricing structures.`;
  } else if (competition >= 40) {
    tacticalPhrase = `With moderate competitor density, establishing a clear value differentiator and leveraging digital marketing will help capture market share.`;
  } else {
    tacticalPhrase = `The fragmented competitive landscape offers a prime window to enter the market and establish first-mover advantage in ${location}.`;
  }

  return `${demandPhrase} ${opportunityPhrase} ${tacticalPhrase}`;
};

// ─── HEADER COMPONENT ───────────────────────────────────────────────────────
const ReportHeader = ({ isSaved, onSave, onDownload, onShare, isLoading }) => (
  <header className="sticky top-0 z-50 w-full bg-background/80 backdrop-blur-xl border-b border-border/60 shadow-sm">
    <div className="max-w-[1400px] mx-auto px-6 h-16 flex items-center justify-between">
      <div className="flex items-center gap-4">
        <Link to="/history-dashboard" className="flex items-center justify-center w-8 h-8 rounded-full hover:bg-muted text-foreground transition-colors">
          <Icon icon="lucide:arrow-left" className="text-xl" />
        </Link>
        <div className="h-4 w-px bg-border"></div>
        <div className="flex flex-col">
          <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Intelligence Report</span>
          <span className="text-sm font-bold text-indigo-600 mt-0.5">BizVision AI</span>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <button 
          onClick={onDownload}
          className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-muted text-sm font-medium transition-colors"
        >
          <Icon icon="lucide:download" className="text-indigo-600" /> PDF
        </button>
        <button 
          onClick={onShare}
          className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-muted text-sm font-medium transition-colors"
        >
          <Icon icon="lucide:share-2" className="text-indigo-600" /> Share
        </button>
        <button 
          onClick={onSave}
          disabled={isLoading}
          className={cn(
            "flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-semibold shadow-sm transition-all",
            isSaved 
              ? "bg-emerald-50 text-emerald-600 border border-emerald-200" 
              : "bg-indigo-600 text-white hover:bg-indigo-700"
          )}
        >
          <Icon icon={isSaved ? "lucide:check" : "lucide:save"} />
          {isLoading ? "Saving..." : isSaved ? "Saved" : "Save to Workspace"}
        </button>
      </div>
    </div>
  </header>
);

// ─── SECTION 1: BUSINESS HEALTH OVERVIEW ───────────────────────────────────
const BusinessHealthOverview = ({ scores }) => {
  const metrics = [
    {
      label: "Health Score",
      value: scores?.viability || 50,
      icon: "lucide:activity",
      color: "indigo"
    },
    {
      label: "Demand Score",
      value: scores?.demand || 50,
      icon: "lucide:users",
      color: "cyan"
    },
    {
      label: "Competition Score",
      value: 100 - (scores?.competition || 50),
      icon: "lucide:target",
      color: "amber"
    },
    {
      label: "Risk Score",
      value: 100 - (scores?.risk || 50),
      icon: "lucide:shield-check",
      color: "emerald"
    }
  ];

  // Map assessment levels dynamically from actual scores, maintaining strict logic consistency
  const assessmentLevels = {
    market: scores?.demand >= 75 ? "High" : scores?.demand >= 45 ? "Medium" : "Low",
    readiness: scores?.viability >= 80 ? "High" : scores?.viability >= 60 ? "Medium" : "Low",
    growth: scores?.trend >= 75 ? "High" : scores?.trend >= 45 ? "Medium" : "Low"
  };

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <h2 className="text-lg font-bold text-foreground mb-6">Business Health Overview</h2>
      
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        {metrics.map((metric, idx) => (
          <div key={idx} className={cn(
            "p-4 rounded-xl border border-border/50",
            metric.color === "indigo" && "bg-indigo-50/20 border-indigo-100/50",
            metric.color === "cyan" && "bg-cyan-50/20 border-cyan-100/50",
            metric.color === "amber" && "bg-amber-50/20 border-amber-100/50",
            metric.color === "emerald" && "bg-emerald-50/20 border-emerald-100/50"
          )}>
            <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">{metric.label}</p>
            <p className={cn(
              "text-2xl font-extrabold",
              metric.color === "indigo" && "text-indigo-600",
              metric.color === "cyan" && "text-cyan-600",
              metric.color === "amber" && "text-amber-600",
              metric.color === "emerald" && "text-emerald-600"
            )}>{metric.value}</p>
            <p className="text-xs text-muted-foreground font-medium">/100</p>
          </div>
        ))}
      </div>

      <div className="pt-6 border-t border-border/50">
        <p className="text-xs font-extrabold text-muted-foreground uppercase tracking-widest mb-4">Quick Assessment</p>
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="text-center">
            <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Market Potential</p>
            <p className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold border ${
              assessmentLevels.market === "High" ? "bg-emerald-50 text-emerald-600 border-emerald-100" : 
              assessmentLevels.market === "Medium" ? "bg-amber-50 text-amber-600 border-amber-100" :
              "bg-red-50 text-red-600 border-red-100"
            }`}>{assessmentLevels.market}</p>
          </div>
          <div className="text-center">
            <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Growth Outlook</p>
            <p className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold border ${
              assessmentLevels.growth === "High" ? "bg-emerald-50 text-emerald-600 border-emerald-100" :
              assessmentLevels.growth === "Medium" ? "bg-amber-50 text-amber-600 border-amber-100" :
              "bg-red-50 text-red-600 border-red-100"
            }`}>{assessmentLevels.growth}</p>
          </div>
          <div className="text-center">
            <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Investment Readiness</p>
            <p className={`inline-flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-bold border ${
              assessmentLevels.readiness === "High" ? "bg-emerald-50 text-emerald-600 border-emerald-100" :
              assessmentLevels.readiness === "Medium" ? "bg-amber-50 text-amber-600 border-amber-100" :
              "bg-red-50 text-red-600 border-red-100"
            }`}>{assessmentLevels.readiness}</p>
          </div>
        </div>
      </div>

      <div className="pt-6 border-t border-border/50">
        <p className="text-xs font-extrabold text-muted-foreground uppercase tracking-widest mb-4">Score Scale & Explanations</p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 text-[11px] leading-relaxed">
          <div className="p-3 bg-indigo-50/20 border border-indigo-100/50 rounded-xl">
            <p className="font-bold text-indigo-800 mb-1">Health (Viability) Score (0–100)</p>
            <p className="text-muted-foreground font-medium"><strong className="text-indigo-600">High (80+):</strong> Strong unit margins & rapid payback. <strong className="text-indigo-600">Med (60-79):</strong> Viable with slight changes. <strong className="text-indigo-600">Low (&lt;60):</strong> High operational friction.</p>
          </div>
          <div className="p-3 bg-cyan-50/20 border border-cyan-100/50 rounded-xl">
            <p className="font-bold text-cyan-800 mb-1">Demand Score (0–100)</p>
            <p className="text-muted-foreground font-medium"><strong className="text-cyan-600">High (75+):</strong> Strong query density & foot traffic interest. <strong className="text-cyan-600">Med (45-74):</strong> Stable local niche. <strong className="text-cyan-600">Low (&lt;45):</strong> Emerging niche/low interest.</p>
          </div>
          <div className="p-3 bg-amber-50/20 border border-amber-100/50 rounded-xl">
            <p className="font-bold text-amber-800 mb-1">Competition Score (0–100)</p>
            <p className="text-muted-foreground font-medium"><strong className="text-amber-600">High (70+):</strong> Dense market; requires distinct brand hook. <strong className="text-amber-600">Med (40-69):</strong> Moderate presence. <strong className="text-amber-600">Low (&lt;40):</strong> Open local market window.</p>
          </div>
          <div className="p-3 bg-emerald-50/20 border border-emerald-100/50 rounded-xl">
            <p className="font-bold text-emerald-800 mb-1">Risk Rating (0–100)</p>
            <p className="text-muted-foreground font-medium"><strong className="text-emerald-600">High (70+):</strong> Supply chain threats/license hurdles. <strong className="text-emerald-600">Med (40-69):</strong> Standard risks. <strong className="text-emerald-600">Low (&lt;40):</strong> Low entry barriers.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

// ─── SECTION 2: EXECUTIVE SUMMARY ──────────────────────────────────────────
const ExecutiveSummary = ({ scores, analysis, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  
  // Dynamic fallback setup in case JSON parsing fails
  const fallbackParagraph = `The ${category.label.toLowerCase()} market presents a viable opportunity based on local demand trends. Success in this category requires focused branding, operational quality control, and robust client acquisition strategies. Competition remains manageable but requires clear service differentiation.`;
  const fallbackInsights = generateDynamicFallbackInsights(metadata, scores);
  const fallbackRecommendation = scores?.viability >= 80
    ? "Initiate pilot testing immediately and launch localized social media booking campaigns."
    : "Validate product packages with target customers to optimize pricing strategies first.";

  // Dynamic Parsing with clean JSON handling
  const parsed = parseJSON(analysis?.executive_summary, {
    paragraph: fallbackParagraph,
    insights: fallbackInsights,
    recommendation: fallbackRecommendation
  });

  const paragraph = parsed.paragraph || fallbackParagraph;
  const insights = parsed.insights && parsed.insights.length === 5 ? parsed.insights : fallbackInsights;
  const recommendation = parsed.recommendation || fallbackRecommendation;

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 lg:col-span-2 flex flex-col">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 rounded-xl bg-indigo-50 flex items-center justify-center">
          <Icon icon="lucide:file-text" className="text-2xl text-indigo-600" />
        </div>
        <div>
          <h2 className="text-2xl font-extrabold tracking-tight">Executive Summary</h2>
          <p className="text-sm text-muted-foreground font-medium">Critical Business Insights</p>
        </div>
      </div>
      
      <div className="mb-8 pb-8 border-b border-border/50">
        <p className="text-sm leading-relaxed text-foreground font-normal">
          {paragraph}
        </p>
      </div>

      <div className="mb-8">
        <div className="pl-6 border-l-2 border-emerald-200/60 space-y-3.5">
          {insights.map((point, idx) => (
            <div key={idx} className="flex gap-3.5 items-start group">
              <span className="text-emerald-500 font-bold text-lg -ml-6 flex-shrink-0 leading-none group-hover:scale-125 transition-transform duration-200">●</span>
              <span className="text-sm text-foreground leading-relaxed pt-0.5">{point}</span>
            </div>
          ))}
        </div>
      </div>
      
      <div className="mt-auto pt-6 border-t border-border/50">
        <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2.5">Recommendation</p>
        <p className="text-sm font-semibold text-indigo-600 leading-relaxed">
          {recommendation}
        </p>
      </div>
    </div>
  );
};

// ─── SECTION 3: BUSINESS RATING ─────────────────────────────────────────────
const BusinessRatingCard = ({ score, confidence }) => {
  const stars = score >= 90 ? 5 : score >= 80 ? 5 : score >= 70 ? 4 : score >= 60 ? 3 : score >= 45 ? 2 : 1;
  const fullStars = Math.floor(stars);
  
  // Map Grade (A+ to D) dynamically
  const grade = score >= 90 ? "A+" : score >= 80 ? "A" : score >= 70 ? "B+" : score >= 60 ? "B" : score >= 45 ? "C" : "D";

  // Map Opportunity Level dynamically
  const opportunityLevel = score >= 75 ? "Strong Opportunity" : score >= 60 ? "Moderate Opportunity" : score >= 45 ? "Limited Opportunity" : "High Risk";
  
  const statusColor = score >= 75 
    ? "from-emerald-50 to-emerald-100/50 border-emerald-200 text-emerald-700" 
    : score >= 45 
      ? "from-amber-50 to-amber-100/50 border-amber-200 text-amber-700" 
      : "from-red-50 to-red-100/50 border-red-200 text-red-700";
      
  const statusBgHover = score >= 75 
    ? "hover:from-emerald-100 hover:to-emerald-200/50" 
    : score >= 45 
      ? "hover:from-amber-100 hover:to-amber-200/50" 
      : "hover:from-red-100 hover:to-red-200/50";
      
  const statusIcon = score >= 75 ? "🟢" : score >= 45 ? "🟡" : "🔴";
  
  const tooltips = [
    "High Risk (D)",
    "Limited Opportunity (C)",
    "Moderate Opportunity (B)",
    "Strong Opportunity (B+/A)",
    "Excellent Business Opportunity (A+)"
  ];

  const renderStars = () => (
    <div className="flex gap-2 justify-center">
      {Array(5).fill(0).map((_, i) => {
        const isFilled = i < fullStars;
        return (
          <div
            key={i}
            className="relative group/star cursor-default"
          >
            <div className="transform transition-all duration-300 ease-out group-hover/star:scale-115 hover:drop-shadow-lg">
              <Icon 
                icon={isFilled ? "lucide:star" : "lucide:star"} 
                className={cn(
                  "text-3xl transition-all duration-300",
                  isFilled ? "text-amber-400 drop-shadow-md" : "text-muted-foreground/30"
                )}
              />
            </div>
            <div className="absolute bottom-full left-1/2 transform -translate-x-1/2 mb-3 opacity-0 group-hover/star:opacity-100 transition-all duration-200 pointer-events-none z-20">
              <div className="bg-slate-900 text-white text-xs font-semibold px-3 py-2 rounded-lg shadow-lg whitespace-nowrap">
                {tooltips[i]}
              </div>
              <div className="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-full w-0 h-0 border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-slate-900"></div>
            </div>
          </div>
        );
      })}
    </div>
  );

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 flex flex-col items-center justify-center relative overflow-hidden group">
      <h2 className="text-lg font-bold text-foreground mb-8 text-center w-full">Business Rating</h2>
      
      <div className="mb-10 transform transition-all duration-300 group-hover:scale-110">
        {renderStars()}
      </div>
      
      <div className="text-center mb-10 w-full space-y-2">
        <div className="flex items-baseline justify-center gap-1">
          <p className="text-5xl font-extrabold text-foreground">{score}</p>
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-wider">/100</p>
        </div>
        <p className="text-sm font-extrabold text-indigo-600">Grade {grade}</p>
        <p className="text-xs text-muted-foreground uppercase tracking-widest">Business Score</p>
      </div>

      <div className="w-full space-y-3.5">
        <div className="text-center p-4 rounded-xl bg-indigo-50/60 border border-indigo-100 hover:border-indigo-300 transition-all duration-200 group/confidence">
          <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider mb-1.5">Confidence Level</p>
          <p className="text-3xl font-extrabold text-indigo-600 transition-transform duration-300 group-hover/confidence:scale-105">{confidence}%</p>
        </div>
        
        <div className={cn(
          "rounded-xl p-4 border text-center cursor-default transition-all duration-300 bg-gradient-to-r hover:shadow-md",
          statusColor,
          statusBgHover
        )}>
          <p className="text-sm font-bold flex items-center justify-center gap-2">
            <span className="text-lg">{statusIcon}</span>
            {opportunityLevel}
          </p>
        </div>
      </div>
    </div>
  );
};

const MarketIntelligenceChart = ({ trends, timeRange, onRangeChange }) => {
  const chartRef = useRef(null);

  const defaultLabels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const defaultPoints = [45, 52, 48, 61, 59, 75, 82, 80, 88, 95, 91, 100];

  const baseLabels = trends && trends.length > 0 ? trends.map(t => t.date) : defaultLabels;
  const basePoints = trends && trends.length > 0 ? trends.map(t => {
    if (t.values && t.values.length > 0) {
      const firstVal = t.values[0];
      const val = Number(firstVal.extracted_value !== undefined ? firstVal.extracted_value : firstVal.value);
      if (!isNaN(val)) return val;
    }
    if (t.value !== undefined && t.value !== null) {
      const val = Number(t.value);
      if (!isNaN(val)) return val;
    }
    return 0;
  }) : defaultPoints;

  let labels = baseLabels;
  let chartPoints = basePoints;

  if (timeRange === '5Y') {
    const currentYear = new Date().getFullYear();
    labels = Array.from({ length: 5 }, (_, i) => String(currentYear - 4 + i));
    const lastVal = basePoints[basePoints.length - 1] || 100;
    const firstVal = basePoints[0] || 40;
    chartPoints = labels.map((_, i) => {
      const ratio = i / 4;
      return Math.round(firstVal * (0.6 + ratio * 0.4) + (lastVal - firstVal) * ratio * 0.5);
    });
  } else if (timeRange === 'All') {
    const currentYear = new Date().getFullYear();
    labels = Array.from({ length: 8 }, (_, i) => String(currentYear - 7 + i));
    const lastVal = basePoints[basePoints.length - 1] || 100;
    const firstVal = basePoints[0] || 40;
    chartPoints = labels.map((_, i) => {
      const ratio = i / 7;
      return Math.round(firstVal * (0.3 + ratio * 0.7) + (lastVal - firstVal) * ratio * 0.4);
    });
  }

  const data = {
    labels: labels,
    datasets: [
      {
        label: 'Search Interest',
        data: chartPoints,
        borderColor: '#6366F1',
        backgroundColor: (context) => {
          const chart = context.chart;
          const { ctx, chartArea } = chart;
          if (!chartArea) return undefined;
          const gradient = ctx.createLinearGradient(0, chartArea.top, 0, chartArea.bottom);
          gradient.addColorStop(0, 'rgba(99, 102, 241, 0.25)');
          gradient.addColorStop(1, 'rgba(99, 102, 241, 0)');
          return gradient;
        },
        borderWidth: 3.5,
        pointBackgroundColor: '#FFFFFF',
        pointBorderColor: '#6366F1',
        pointBorderWidth: 2,
        pointRadius: 4,
        pointHoverRadius: 6,
        fill: true,
        tension: 0.35,
      },
    ],
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: '#0F172A',
        padding: 12,
        titleFont: { family: 'Inter', size: 13 },
        bodyFont: { family: 'Inter', size: 14, weight: 'bold' },
        displayColors: false,
        cornerRadius: 8,
      },
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { 
          font: { family: 'Inter', weight: '500', size: 11 }, 
          color: '#64748B',
          maxTicksLimit: 8,
          maxRotation: 0,
          minRotation: 0
        },
      },
      y: {
        grid: { color: '#E2E8F0', borderDash: [5, 5] },
        ticks: { font: { family: 'Inter', weight: '500', size: 11 }, color: '#64748B', stepSize: 20 },
      },
    },
    interaction: { intersect: false, mode: 'index' },
  };

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
            <Icon icon="lucide:line-chart" className="text-xl text-indigo-600" />
          </div>
          <div>
            <h3 className="text-xl font-extrabold tracking-tight">Market Intelligence</h3>
            <p className="text-sm text-muted-foreground font-medium">Search volume & industry growth trends</p>
          </div>
        </div>
        <div className="flex bg-muted/50 p-1 rounded-lg border border-border self-start">
          {['12M', '5Y', 'All'].map((range) => (
            <button
              key={range}
              onClick={() => onRangeChange(range)}
              className={cn(
                "px-4 py-1.5 text-xs font-bold rounded-md transition-all",
                timeRange === range ? "bg-white shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"
              )}
            >
              {range}
            </button>
          ))}
        </div>
      </div>
      
      <div className="h-80 w-full overflow-hidden relative">
        <Line ref={chartRef} data={data} options={options} />
      </div>
    </div>
  );
};

// ─── SECTION 5: COMPETITOR INTELLIGENCE ─────────────────────────────────────
const CompetitorIntelligence = ({ competitors, analysis, scores, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  
  const defaultCompetitors = [
    {
      initials: 'PB',
      name: 'Pawsome Bites',
      rating: 4.8,
      reviews: '2.4k',
      badge: 'Market Leader',
      colorClass: 'bg-indigo-600',
      differentiator: "Highly established local player with premium formulations but limited home delivery coverage."
    },
    {
      initials: 'GN',
      name: 'GreenNose Feeders',
      rating: 4.2,
      reviews: '842',
      colorClass: 'bg-cyan-500',
      differentiator: "Eco-friendly branding with a moderate customer review rate, limited product customization."
    }
  ];

  const defaultGapAnalysis = {
    premium_segment: `Very few high-quality ${category.label.toLowerCase()} choices exist in this local market, leaving room for a premium option.`,
    differentiation_potential: "You can stand out easily by using simple online tools, home delivery, and better customer support.",
    market_saturation: "Competitor density is moderate, but they mostly use old-school methods and ignore digital marketing.",
    expansion_opportunity: "Once you build a stable customer base, you can expand easily to nearby high-income areas."
  };

  // Dynamic Parsing of LLM analysis
  const parsed = parseJSON(analysis?.competitor_analysis, {
    competitors: [],
    gap_analysis: defaultGapAnalysis
  });

  const parsedComps = parsed.competitors || [];
  const gapAnalysis = parsed.gap_analysis || defaultGapAnalysis;

  const mappedCompetitors = competitors && competitors.length > 0
    ? competitors.slice(0, 3).map((c, idx) => {
        const matchingParsed = parsedComps.find(pc => pc.name && pc.name.toLowerCase().includes((c.title || "").toLowerCase()));
        return {
          initials: c.title ? c.title.slice(0, 2).toUpperCase() : 'CO',
          name: c.title || 'Competitor',
          rating: Number(c.rating) || 4.0,
          reviews: c.reviews ? String(c.reviews) : '0',
          badge: idx === 0 ? 'Market Leader' : undefined,
          colorClass: idx % 2 === 0 ? 'bg-indigo-600' : 'bg-cyan-500',
          differentiator: matchingParsed?.differentiator || c.differentiator || "Local incumbent servicing general customer segments.",
          tags: [
            { label: c.address ? c.address.split(',')[0] : 'Local', type: 'success' }
          ]
        };
      })
    : defaultCompetitors;

  const avgRating = mappedCompetitors.reduce((sum, c) => sum + c.rating, 0) / mappedCompetitors.length;
  const saturation = competitors?.length > 5 ? "High" : competitors?.length > 2 ? "Medium" : "Low";
  const differentiation = scores?.competition < 50 ? "Strong" : scores?.competition < 70 ? "Moderate" : "Weak";

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <div className="flex items-center gap-3 mb-8">
        <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center">
          <Icon icon="lucide:crosshair" className="text-xl text-amber-600" />
        </div>
        <div>
          <h3 className="text-lg font-bold tracking-tight">Competitor Intelligence</h3>
          <p className="text-sm text-muted-foreground font-medium">Top market players & differentiator gaps</p>
        </div>
      </div>

      <div className="space-y-4 mb-8">
        {mappedCompetitors.map((comp, idx) => (
          <div key={idx} className="p-4 rounded-xl border border-border/50 hover:shadow-md transition-shadow bg-background/50">
            <div className="flex justify-between items-start">
              <div className="flex items-start gap-3">
                <div className={cn("w-10 h-10 rounded-lg text-white flex items-center justify-center font-bold text-sm mt-0.5", comp.colorClass)}>
                  {comp.initials}
                </div>
                <div>
                  <h4 className="font-bold text-sm">{comp.name}</h4>
                  <div className="flex items-center gap-1 text-xs text-amber-500 font-bold mt-0.5 mb-1.5">
                    <Icon icon="lucide:star" /> {comp.rating} <span className="text-muted-foreground font-medium">({comp.reviews})</span>
                  </div>
                  <p className="text-xs text-muted-foreground leading-relaxed font-normal">{comp.differentiator}</p>
                </div>
              </div>
              {comp.badge && (
                <span className="bg-indigo-50 text-indigo-600 px-2 py-1 rounded text-[10px] font-bold uppercase tracking-wider border border-indigo-100">
                  {comp.badge}
                </span>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Market Gap Analysis (Section 5 Addition) */}
      <div className="mb-8 pt-6 border-t border-border/50">
        <div className="flex items-center gap-2 mb-4">
          <Icon icon="lucide:split" className="text-lg text-indigo-600" />
          <h4 className="text-sm font-bold text-foreground">Market Gap Analysis</h4>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl border border-border/30 bg-background/25">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Premium Options</span>
            <p className="text-xs text-muted-foreground leading-relaxed font-normal">{gapAnalysis.premium_segment}</p>
          </div>
          <div className="p-4 rounded-xl border border-border/30 bg-background/25">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">How to Stand Out</span>
            <p className="text-xs text-muted-foreground leading-relaxed font-normal">{gapAnalysis.differentiation_potential}</p>
          </div>
          <div className="p-4 rounded-xl border border-border/30 bg-background/25">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Saturation Level</span>
            <p className="text-xs text-muted-foreground leading-relaxed font-normal">{gapAnalysis.market_saturation}</p>
          </div>
          <div className="p-4 rounded-xl border border-border/30 bg-background/25">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Expansion Potential</span>
            <p className="text-xs text-muted-foreground leading-relaxed font-normal">{gapAnalysis.expansion_opportunity}</p>
          </div>
        </div>
      </div>

      <div className="pt-6 border-t border-border/50 grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="text-center">
          <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider mb-1">Competitors Found</p>
          <p className="text-lg font-extrabold text-foreground">{competitors?.length || 2}</p>
        </div>
        <div className="text-center">
          <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider mb-1">Avg Rating</p>
          <p className="text-lg font-extrabold text-amber-600">{avgRating.toFixed(1)}★</p>
        </div>
        <div className="text-center">
          <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider mb-1">Market Saturation</p>
          <p className={`text-xs font-bold px-2 py-1 rounded border inline-block ${
            saturation === "High" ? "bg-red-50 text-red-600 border-red-100" :
            saturation === "Medium" ? "bg-amber-50 text-amber-600 border-amber-100" :
            "bg-emerald-50 text-emerald-600 border-emerald-100"
          }`}>{saturation}</p>
        </div>
        <div className="text-center">
          <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider mb-1">Differentiation</p>
          <p className={`text-xs font-bold px-2 py-1 rounded border inline-block ${
            differentiation === "Strong" ? "bg-emerald-50 text-emerald-600 border-emerald-100" :
            differentiation === "Moderate" ? "bg-amber-50 text-amber-600 border-amber-100" :
            "bg-red-50 text-red-600 border-red-100"
          }`}>{differentiation}</p>
        </div>
      </div>
    </div>
  );
};

// ─── SECTION 4 Addition: MARKET INSIGHTS CARD ──────────────────────────────
const MarketInsightsCard = ({ text, scores, trends }) => {
  const trendDirection = trends && trends.length > 1 
    ? trends[trends.length - 1].value > trends[0].value 
      ? "Upward ↗"
      : "Downward ↘"
    : "Stable →";

  // Dynamic Parsing of LLM analysis
  const defaultInsights = [
    `Search interest trend shows ${trendDirection} momentum.`,
    `Industry demand indicator: ${scores?.demand >= 75 ? "Strong" : scores?.demand >= 45 ? "Moderate" : "Weak"}.`,
    `Market query volume signal: ${scores?.demand || 50}/100.`,
    "Customer search query velocity remains consistent."
  ];

  const parsed = parseJSON(text, {
    insights: defaultInsights,
    interpretation: `Current query analysis shows stable category search rates. The local market remains receptive to products aligned with premium and organic lifestyle trends.`
  });

  const insightsList = parsed.insights || defaultInsights;
  const interpretationText = parsed.interpretation || "";

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 flex flex-col justify-between">
      <div>
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
            <Icon icon="lucide:trending-up" className="text-xl text-indigo-600" />
          </div>
          <div>
            <h3 className="text-lg font-bold tracking-tight">Market Intelligence</h3>
            <p className="text-sm text-muted-foreground font-medium">Demand & Growth Signals</p>
          </div>
        </div>
        
        <div className="space-y-3">
          {insightsList.slice(0, 4).map((insight, idx) => (
            <div key={idx} className="flex gap-3 items-start">
              <span className="text-emerald-500 font-bold text-lg mt-0.5 flex-shrink-0 leading-none">●</span>
              <span className="text-sm text-foreground pt-0.5 leading-relaxed font-normal">{insight}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Market Interpretation paragraph (Section 4 Addition) */}
      {interpretationText && (
        <div className="mt-6 pt-6 border-t border-border/50">
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Market Interpretation</p>
          <p className="text-xs leading-relaxed text-foreground font-medium">{interpretationText}</p>
        </div>
      )}
    </div>
  );
};

// ─── SECTION 7: SWOT ANALYSIS ──────────────────────────────────────────────
const SWOTAnalysis = ({ scores, competitors, analysis, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  const fallbacks = generateFallbackSWOT(metadata?.idea_text, category);

  // Parse Strengths & Opportunities from opportunity_analysis
  const parsedOpp = parseJSON(analysis?.opportunity_analysis, {
    strengths: fallbacks.strengths,
    opportunities: fallbacks.opportunities
  });

  // Parse Weaknesses & Threats from risk_analysis
  const parsedRisk = parseJSON(analysis?.risk_analysis, {
    weaknesses: fallbacks.weaknesses,
    threats: fallbacks.threats
  });

  const swot = {
    strengths: parsedOpp.strengths && parsedOpp.strengths.length === 2 ? parsedOpp.strengths : fallbacks.strengths,
    weaknesses: parsedRisk.weaknesses && parsedRisk.weaknesses.length === 2 ? parsedRisk.weaknesses : fallbacks.weaknesses,
    opportunities: parsedOpp.opportunities && parsedOpp.opportunities.length === 2 ? parsedOpp.opportunities : fallbacks.opportunities,
    threats: parsedRisk.threats && parsedRisk.threats.length === 2 ? parsedRisk.threats : fallbacks.threats
  };

  const SWOT_SECTION = [
    { title: "Strengths", items: swot.strengths, icon: "lucide:zap", color: "emerald", dotColor: "text-emerald-500" },
    { title: "Weaknesses", items: swot.weaknesses, icon: "lucide:alert-circle", color: "amber", dotColor: "text-amber-500" },
    { title: "Opportunities", items: swot.opportunities, icon: "lucide:lightbulb", color: "indigo", dotColor: "text-indigo-500" },
    { title: "Threats", items: swot.threats, icon: "lucide:shield-alert", color: "red", dotColor: "text-red-500" }
  ];

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <h2 className="text-lg font-bold text-foreground mb-8">SWOT Analysis</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {SWOT_SECTION.map((section, idx) => (
          <div key={idx} className={cn(
            "p-6 rounded-xl border-2 bg-gradient-to-br",
            section.color === "emerald" && "bg-emerald-50/20 border-emerald-200/50",
            section.color === "amber" && "bg-amber-50/20 border-amber-200/50",
            section.color === "indigo" && "bg-indigo-50/20 border-indigo-200/50",
            section.color === "red" && "bg-red-50/20 border-red-200/50"
          )}>
            <div className="flex items-center gap-2 mb-4">
              <Icon icon={section.icon} className={cn(
                "text-xl",
                section.color === "emerald" && "text-emerald-600",
                section.color === "amber" && "text-amber-600",
                section.color === "indigo" && "text-indigo-600",
                section.color === "red" && "text-red-600"
              )} />
              <h3 className={cn(
                "font-bold",
                section.color === "emerald" && "text-emerald-700",
                section.color === "amber" && "text-amber-700",
                section.color === "indigo" && "text-indigo-700",
                section.color === "red" && "text-red-700"
              )}>{section.title}</h3>
            </div>
            <ul className="space-y-2.5">
              {section.items.slice(0, 2).map((item, i) => (
                <li key={i} className="text-xs leading-relaxed text-foreground flex gap-2.5 font-normal">
                  <span className={cn(section.dotColor, "font-bold text-lg flex-shrink-0 leading-none")}>●</span>
                  <span className="pt-0.5">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── SECTION 8: KEY OPPORTUNITIES ──────────────────────────────────────────
const KeyOpportunities = ({ text, analysis, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  const fallbackOpps = [
    `Launch a premium custom product collection targeting high-income ${category.label.toLowerCase()} segments.`,
    "Build a recurring subscription plan or membership structure to stabilize client lifetime value.",
    "Form strategic distribution partnerships with complementary local boutique storefronts.",
    "Deploy social media video marketing to showcase production craftsmanship and quality.",
    "Introduce white-label corporate gift packaging collections for seasonal festivals."
  ];

  // Dynamic Parsing of LLM analysis
  const parsed = parseJSON(analysis?.opportunity_analysis, {
    key_opportunities: fallbackOpps
  });

  const opportunities = parsed.key_opportunities && parsed.key_opportunities.length > 0 
    ? parsed.key_opportunities 
    : fallbackOpps;

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 flex flex-col">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
          <Icon icon="lucide:lightbulb" className="text-xl text-indigo-600" />
        </div>
        <div>
          <h3 className="text-lg font-bold tracking-tight">Key Opportunities</h3>
          <p className="text-sm text-muted-foreground font-medium">Strategic growth avenues</p>
        </div>
      </div>
      
      <div className="space-y-2.5">
        {opportunities.slice(0, 5).map((opp, idx) => (
          <div key={idx} className="flex gap-3 items-start p-3 rounded-lg bg-indigo-50/40 border border-indigo-100/50 hover:bg-indigo-50/60 hover:border-indigo-100 transition-colors">
            <span className="text-emerald-500 font-bold text-lg mt-0.5 flex-shrink-0 leading-none">●</span>
            <span className="text-sm text-foreground pt-0.5 leading-relaxed font-normal">{opp}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── SECTION 9: RECOMMENDED ACTION PLAN ────────────────────────────────────
const RecommendedActionPlan = ({ scores, analysis, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  const fallbackRoadmap = generateFallbackRoadmap(metadata?.idea_text, category);

  // Dynamic Parsing of LLM analysis
  const parsed = parseJSON(analysis?.opportunity_analysis, {
    roadmap: fallbackRoadmap
  });

  const phases = parsed.roadmap && parsed.roadmap.length === 4 ? parsed.roadmap : fallbackRoadmap;

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <h2 className="text-lg font-bold text-foreground mb-8">Recommended Action Plan</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {phases.map((phase, idx) => (
          <div key={idx} className="relative">
            <div className="p-5 rounded-xl border-2 border-indigo-100 bg-indigo-50/20">
              <p className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">{phase.phase}</p>
              <h4 className="text-sm font-bold text-foreground mb-3">{phase.title}</h4>
              <ul className="space-y-2">
                {phase.tasks.map((task, t) => (
                  <li key={t} className="text-xs text-muted-foreground flex gap-2.5 leading-normal font-normal">
                    <span className="text-emerald-500 font-bold text-base flex-shrink-0 leading-none">●</span>
                    <span className="pt-0.5">{task}</span>
                  </li>
                ))}
              </ul>
            </div>
            {idx < phases.length - 1 && (
              <div className="hidden lg:block absolute -right-2 top-1/2 transform -translate-y-1/2 text-indigo-300">
                <Icon icon="lucide:arrow-right" className="text-2xl" />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── SECTION 6: DEMAND & REVENUE POTENTIAL ─────────────────────────────────
const DemandRevenueAnalysis = ({ scores, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  const type = category.type;
  const demand = scores?.demand || 50;
  const viability = scores?.viability || 50;

  // Potential Customers calculation based strictly on category and demand score
  let custCountNum = 0;
  let custIcon = "👥";
  let custLabel = "Potential Customers";
  if (type === "saas") {
    custCountNum = Math.round(500 + demand * 30);
    custLabel = "Potential Subscribers";
    custIcon = "💻";
  } else if (type === "digital_platform") {
    custCountNum = Math.round(2000 + demand * 400);
    custLabel = "Active Users";
    custIcon = "🌐";
  } else if (type === "local_service") {
    custCountNum = Math.round(800 + demand * 20);
    custLabel = "Monthly Customers";
    custIcon = "🏠";
  } else if (type === "physical_product") {
    custCountNum = Math.round(1000 + demand * 50);
    custLabel = "Monthly Sales Vol";
    custIcon = "📦";
  } else {
    custCountNum = Math.round(50 + demand * 2);
    custLabel = "Target Clients";
    custIcon = "🤝";
  }
  const custCount = custCountNum.toLocaleString('en-IN') + "+";

  // Average Customer Spending (dynamic based on category & demand tier)
  let spending = "";
  if (type === "saas") {
    if (demand >= 75) spending = "₹1,500 – ₹5,000 /mo";
    else if (demand >= 45) spending = "₹800 – ₹2,500 /mo";
    else spending = "₹299 – ₹999 /mo";
  } else if (type === "digital_platform") {
    if (demand >= 75) spending = "₹200 – ₹600 /user";
    else if (demand >= 45) spending = "₹100 – ₹300 /user";
    else spending = "₹30 – ₹120 /user";
  } else if (type === "local_service") {
    if (demand >= 75) spending = "₹600 – ₹1,800 /visit";
    else if (demand >= 45) spending = "₹300 – ₹900 /visit";
    else spending = "₹150 – ₹450 /visit";
  } else if (type === "physical_product") {
    if (demand >= 75) spending = "₹800 – ₹2,500 /unit";
    else if (demand >= 45) spending = "₹400 – ₹1,200 /unit";
    else spending = "₹200 – ₹500 /unit";
  } else {
    if (demand >= 75) spending = "₹15,000 – ₹60,000 /contract";
    else if (demand >= 45) spending = "₹8,000 – ₹25,000 /contract";
    else spending = "₹3,000 – ₹10,000 /contract";
  }

  // Revenue Potential calculations (dynamic based on category & demand tier)
  let revSmall = "", revMed = "", revLarge = "";
  if (type === "saas") {
    if (demand >= 75) {
      revSmall = "₹2.5 Lakh"; revMed = "₹8 Lakh"; revLarge = "₹20 Lakh+";
    } else if (demand >= 45) {
      revSmall = "₹1.2 Lakh"; revMed = "₹4 Lakh"; revLarge = "₹10 Lakh+";
    } else {
      revSmall = "₹40,000"; revMed = "₹1.5 Lakh"; revLarge = "₹4 Lakh+";
    }
  } else if (type === "digital_platform") {
    if (demand >= 75) {
      revSmall = "₹1.5 Lakh"; revMed = "₹5 Lakh"; revLarge = "₹15 Lakh+";
    } else if (demand >= 45) {
      revSmall = "₹70,000"; revMed = "₹2.5 Lakh"; revLarge = "₹7 Lakh+";
    } else {
      revSmall = "₹20,000"; revMed = "₹80,000"; revLarge = "₹2.5 Lakh+";
    }
  } else if (type === "local_service") {
    if (demand >= 75) {
      revSmall = "₹2 Lakh"; revMed = "₹6 Lakh"; revLarge = "₹15 Lakh+";
    } else if (demand >= 45) {
      revSmall = "₹90,000"; revMed = "₹3 Lakh"; revLarge = "₹7 Lakh+";
    } else {
      revSmall = "₹30,000"; revMed = "₹1 Lakh"; revLarge = "₹3 Lakh+";
    }
  } else if (type === "physical_product") {
    if (demand >= 75) {
      revSmall = "₹3 Lakh"; revMed = "₹10 Lakh"; revLarge = "₹25 Lakh+";
    } else if (demand >= 45) {
      revSmall = "₹1.2 Lakh"; revMed = "₹4.5 Lakh"; revLarge = "₹12 Lakh+";
    } else {
      revSmall = "₹40,000"; revMed = "₹1.5 Lakh"; revLarge = "₹4 Lakh+";
    }
  } else {
    if (demand >= 75) {
      revSmall = "₹4 Lakh"; revMed = "₹12 Lakh"; revLarge = "₹30 Lakh+";
    } else if (demand >= 45) {
      revSmall = "₹1.8 Lakh"; revMed = "₹6 Lakh"; revLarge = "₹15 Lakh+";
    } else {
      revSmall = "₹60,000"; revMed = "₹2 Lakh"; revLarge = "₹5 Lakh+";
    }
  }

  // Market Demand
  const demandLevel = demand >= 75 ? "High" : demand >= 45 ? "Medium" : "Low";
  const demandColor = demand >= 75 ? "text-emerald-600 bg-emerald-50 border border-emerald-100" : demand >= 45 ? "text-amber-600 bg-amber-50 border border-amber-100" : "text-red-600 bg-red-50 border border-red-100";

  // Business Opportunity
  const oppLevel = viability >= 75 ? "Strong" : viability >= 50 ? "Moderate" : "Limited";
  const oppColor = viability >= 75 ? "text-indigo-600 bg-indigo-50 border border-indigo-100" : viability >= 50 ? "text-cyan-600 bg-cyan-50 border border-cyan-100" : "text-slate-600 bg-slate-50 border border-slate-100";

  // Revenue Confidence (Section 6 Addition)
  const confidenceLevel = demand >= 75 ? "High" : demand >= 45 ? "Medium" : "Low";
  const confidenceColor = demand >= 75 ? "text-emerald-600 bg-emerald-50 border border-emerald-100" : demand >= 45 ? "text-amber-600 bg-amber-50 border border-amber-100" : "text-red-600 bg-red-50 border border-red-100";

  const keyInsight = generateDynamicKeyInsight(metadata, scores);

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <div className="flex items-center gap-3 mb-8">
        <div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center">
          <Icon icon="lucide:shopping-bag" className="text-xl text-cyan-600" />
        </div>
        <div>
          <h2 className="text-lg font-bold tracking-tight">Demand & Revenue Potential</h2>
          <p className="text-sm text-muted-foreground font-medium">Market sizing & monetization</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 mb-6">
        <div className="p-4 rounded-xl border border-border/50 bg-background/30">
          <span className="text-xs font-bold text-muted-foreground block mb-2 uppercase tracking-wider">{custLabel}</span>
          <span className="text-2xl font-extrabold text-indigo-600">{custIcon} {custCount}</span>
        </div>

        <div className="p-4 rounded-xl border border-border/50 bg-background/30">
          <span className="text-xs font-bold text-muted-foreground block mb-2 uppercase tracking-wider">Avg Customer Spend</span>
          <span className="text-2xl font-extrabold text-foreground">💰 {spending}</span>
        </div>
      </div>

      <div className="p-4 rounded-xl border border-border/50 bg-background/30 mb-6">
        <span className="text-xs font-bold text-muted-foreground block mb-3 uppercase tracking-wider">Revenue Potential (INR)</span>
        <div className="grid grid-cols-3 gap-3">
          <div className="p-3 bg-card rounded-lg border border-border/30 text-center">
            <p className="text-muted-foreground font-medium text-[11px] mb-1">Small Scale</p>
            <p className="font-extrabold text-foreground">{revSmall}/mo</p>
          </div>
          <div className="p-3 bg-indigo-50/50 rounded-lg border border-indigo-100 text-center">
            <p className="text-indigo-600 font-bold text-[11px] mb-1">Medium Scale</p>
            <p className="font-extrabold text-indigo-700">{revMed}/mo</p>
          </div>
          <div className="p-3 bg-emerald-50/50 rounded-lg border border-emerald-100 text-center">
            <p className="text-emerald-600 font-bold text-[11px] mb-1">Large Scale</p>
            <p className="font-extrabold text-emerald-700">{revLarge}/mo</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <div className="p-4 rounded-xl border border-border/50 bg-background/30 flex flex-col justify-center text-center">
          <span className="text-xs font-bold text-muted-foreground block mb-2 uppercase tracking-wider">Market Demand</span>
          <span className={`inline-flex items-center justify-center gap-1 px-3 py-1.5 rounded-lg text-xs font-bold border ${demandColor}`}>
            📈 {demandLevel}
          </span>
        </div>

        <div className="p-4 rounded-xl border border-border/50 bg-background/30 flex flex-col justify-center text-center">
          <span className="text-xs font-bold text-muted-foreground block mb-2 uppercase tracking-wider">Business Opportunity</span>
          <span className={`inline-flex items-center justify-center gap-1 px-3 py-1.5 rounded-lg text-xs font-bold border ${oppColor}`}>
            💡 {oppLevel}
          </span>
        </div>

        {/* Revenue Confidence (Section 6 Addition) */}
        <div className="p-4 rounded-xl border border-border/50 bg-background/30 flex flex-col justify-center text-center">
          <span className="text-xs font-bold text-muted-foreground block mb-2 uppercase tracking-wider">Revenue Confidence</span>
          <span className={`inline-flex items-center justify-center gap-1 px-3 py-1.5 rounded-lg text-xs font-bold border ${confidenceColor}`}>
            💡 {confidenceLevel}
          </span>
        </div>
      </div>

      {keyInsight && (
        <div className="mt-6 pt-4 border-t border-border/60">
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-2">Key Insight</p>
          <p className="text-sm text-foreground font-medium leading-relaxed font-normal">{keyInsight}</p>
        </div>
      )}
    </div>
  );
};

// ─── SECTION 10: AI BRAND NAME SUGGESTIONS ──────────────────────────────────
const BrandNameRationale = ({ businessNames, metadata }) => {
  const category = getBusinessCategory(metadata?.idea_text);
  
  const defaultNames = [
    { name: 'VedicVeg', brand_uniqueness: 94, tagline: 'Purity on Every Plate.', rationale: '💡 Connection to category: Direct tie-in with organic clean dining.\n💡 Emotional appeal: Instills confidence and health-focused purity.\n💡 Brand perception: High-end quality food supplier.\n💡 Market suitability: Fits urban audience seeking organic food.', why_recommended: "Best Recommended Option: Strongly connects with pure culinary roots and has a premium local appeal." },
    { name: 'PureFeast', brand_uniqueness: 88, tagline: 'Traditional Taste, Modern Hygiene.', rationale: '💡 Connection to category: Highlights vegetarian hospitality.\n💡 Emotional appeal: Generous and inviting dining experience.\n💡 Brand perception: Warm, clean, family-friendly.\n💡 Market suitability: High recall value for local families.', why_recommended: "Great local option: Excellent local community presence." },
    { name: 'GreenSparks', brand_uniqueness: 80, tagline: 'Innovating the Vegetarian Kitchen.', rationale: '💡 Connection to category: Modern, chef-driven veg recipes.\n💡 Emotional appeal: Contemporary and energetic lifestyle focus.\n💡 Brand perception: High-quality modern veg cafe.\n💡 Market suitability: Fits urban demographic and online deliveries.', why_recommended: "Excellent alternative: Highly brandable name for modern demographics." }
  ];

  const names = businessNames && businessNames.length > 0 ? businessNames : defaultNames;

  // The first item in the list is defined as the best recommendation
  const recommendedName = names[0] || defaultNames[0];

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <div className="flex items-center gap-3 mb-8">
        <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
          <Icon icon="lucide:tags" className="text-xl text-indigo-600" />
        </div>
        <div>
          <h2 className="text-lg font-bold tracking-tight">AI Brand Name Suggestions</h2>
          <p className="text-sm text-muted-foreground font-medium">AI-generated branding concepts</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
        {names.slice(0, 3).map((n, idx) => (
          <div key={idx} className="p-6 rounded-xl border border-border/50 bg-background/50 hover:shadow-md hover:border-indigo-200 transition-all flex flex-col justify-between">
            <div>
              <div className="flex items-start justify-between gap-3 mb-1">
                <h3 className="text-base font-bold text-foreground">{n.name}</h3>
                <span className="bg-indigo-50 text-indigo-600 border border-indigo-100 text-[10px] font-bold px-2.5 py-1 rounded-lg whitespace-nowrap">
                  {n.brand_uniqueness}% Unique
                </span>
              </div>
              <p className="text-xs italic text-indigo-600 font-bold mb-4">"{n.tagline || 'Purity on Every Plate.'}"</p>
              
              <div className="space-y-1.5">
                <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-2">Highlights</p>
                <div className="text-xs text-muted-foreground leading-relaxed whitespace-pre-line font-normal">
                  {n.rationale}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Best Recommended Name Section (Section 10 Addition) */}
      {recommendedName && (
        <div className="p-6 rounded-xl border-2 border-indigo-200 bg-indigo-50/20 flex flex-col md:flex-row items-center justify-between gap-4">
          <div>
            <span className="text-[10px] text-indigo-600 uppercase font-extrabold tracking-wider block mb-1">Best Recommended Name</span>
            <h4 className="text-lg font-extrabold text-indigo-900">{recommendedName.name}</h4>
            <p className="text-xs text-indigo-700/80 mt-1 leading-relaxed font-medium">
              {recommendedName.why_recommended || "This name offers the strongest combination of category relevance, trademark availability, and brand recall."}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};



// ─── SECTION 11: FINAL VERDICT ─────────────────────────────────────────────
const FinalVerdict = ({ scores, analysis, onGenerate, onSave, isLoading, metadata }) => {
  const viability = scores?.viability || 50;
  const stars = viability >= 90 ? 5 : viability >= 80 ? 5 : viability >= 70 ? 4 : viability >= 60 ? 3 : viability >= 45 ? 2 : 1;
  const fullStars = Math.floor(stars);
  
  const statusColor = viability >= 75 ? "from-emerald-600 to-emerald-700" : 
                      viability >= 45 ? "from-amber-600 to-amber-700" : 
                      "from-red-600 to-red-700";
  
  const statusBadge = viability >= 75 ? "🟢 Strong Opportunity" : 
                      viability >= 45 ? "🟡 Proceed with Caution" : 
                      "🔴 High Risk";

  const category = getBusinessCategory(metadata?.idea_text);
  const fallbackSWOT = generateFallbackSWOT(metadata?.idea_text, category);

  const fallbackReasons = generateFallbackVerdictReasons(scores);
  const fallbackStrengths = fallbackSWOT.strengths;
  const fallbackRisks = [
    "High initial client acquisition costs.",
    "Potential operational scalability bottleneck."
  ];
  const fallbackNextStep = viability >= 75
    ? "Initiate a localized MVP launch within 14 days."
    : "Validate unit economic models before launching.";

  // Dynamic Parsing of LLM analysis
  const parsed = parseJSON(analysis?.final_recommendation, {
    reasons: fallbackReasons,
    strengths: fallbackStrengths,
    risks: fallbackRisks,
    next_step: fallbackNextStep
  });

  const reasons = parsed.reasons && parsed.reasons.length === 3 ? parsed.reasons : fallbackReasons;
  const strengths = parsed.strengths && parsed.strengths.length === 2 ? parsed.strengths : fallbackStrengths;
  const risks = parsed.risks && parsed.risks.length === 2 ? parsed.risks : fallbackRisks;
  const nextStep = parsed.next_step || fallbackNextStep;

  return (
    <div className={`bg-gradient-to-r ${statusColor} rounded-[2rem] p-8 md:p-12 shadow-2xl relative overflow-hidden flex flex-col gap-8 text-white`}>
      <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full blur-[100px] pointer-events-none -translate-y-1/2 translate-x-1/3"></div>
      <div className="absolute bottom-0 left-0 w-64 h-64 bg-white/5 rounded-full blur-[80px] pointer-events-none translate-y-1/2 -translate-x-1/4"></div>
      
      <div className="relative z-10">
        <p className="text-xs font-bold uppercase tracking-widest text-white/80 mb-8">Final Verdict</p>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-3">Business Potential</p>
            <div className="flex gap-1">
              {Array(5).fill(0).map((_, i) => (
                <span key={i} className="text-2xl">
                  {i < fullStars ? "★" : "☆"}
                </span>
              ))}
            </div>
          </div>
          
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Confidence Score</p>
            <p className="text-3xl font-extrabold">{viability}%</p>
          </div>
          
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Status</p>
            <p className="text-lg font-bold">{statusBadge}</p>
          </div>
        </div>

        {/* Why This Rating (Section 11 Addition) */}
        <div className="mb-8 pb-8 border-b border-white/20">
          <h3 className="text-xs font-bold uppercase tracking-wider text-white/70 mb-4">Why This Rating?</h3>
          <ul className="space-y-3 pl-6 border-l border-white/20">
            {reasons.slice(0, 3).map((reason, idx) => (
              <li key={idx} className="text-sm leading-relaxed font-medium flex gap-2">
                <span className="text-white/60 font-bold">•</span>
                <span>{reason}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-white/70 mb-3">Key Strengths</h3>
            <ul className="space-y-2.5">
              {strengths.slice(0, 2).map((strength, i) => (
                <li key={i} className="text-sm flex gap-3 leading-relaxed font-normal">
                  <span className="text-lg flex-shrink-0 leading-none">●</span> 
                  <span className="pt-0.5">{strength}</span>
                </li>
              ))}
            </ul>
          </div>
          
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-white/70 mb-3">Key Risks</h3>
            <ul className="space-y-2.5">
              {risks.slice(0, 2).map((risk, i) => (
                <li key={i} className="text-sm flex gap-3 leading-relaxed font-normal">
                  <span className="text-lg flex-shrink-0 leading-none">●</span> 
                  <span className="pt-0.5">{risk}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Recommended Next Step (Section 11 Addition) */}
        <div className="pt-6 border-t border-white/25">
          <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Recommended Next Step</p>
          <p className="text-sm font-semibold text-white leading-relaxed">{nextStep}</p>
        </div>
      </div>

      <div className="relative z-10 pt-6 border-t border-white/20 grid grid-cols-1 md:grid-cols-2 gap-4">
        <button 
          onClick={onGenerate}
          disabled={isLoading}
          className="bg-white text-indigo-600 hover:bg-indigo-50 px-6 py-3 rounded-lg font-bold shadow-lg transition-all flex items-center justify-center gap-2 disabled:opacity-70"
        >
          <Icon icon={isLoading ? "lucide:loader-2" : "lucide:rocket"} className={cn("text-lg", isLoading && "animate-spin")} />
          {isLoading ? "Generating..." : "Generate Business Plan"}
        </button>
        <button 
          onClick={onSave}
          className="bg-white/10 hover:bg-white/20 text-white border border-white/30 px-6 py-3 rounded-lg font-bold transition-all flex items-center justify-center gap-2"
        >
          <Icon icon="lucide:bookmark" className="text-lg" /> Save Report
        </button>
      </div>
    </div>
  );
};

// ─── MAIN REPORT VIEW ───────────────────────────────────────────────────────
const IntelligenceReport = () => {
  const location = useLocation();
  const reportPayload = location.state?.report;

  const fallbackReport = {
    metadata: {
      idea_text: 'Organic Pet Food in Hyderabad',
      location: 'Hyderabad, India',
      business_type: 'E-commerce & Manufacturing'
    },
    scores: {
      viability: 82,
      demand: 91,
      opportunity: 88,
      risk: 14,
      competition: 50,
      trend: 80
    },
    analysis: {
      executive_summary: JSON.stringify({
        paragraph: "The organic pet food market in Hyderabad presents a high-growth opportunity driven by localized pet humanization and increasing consumer disposable incomes. Launching a premium manufacturing and e-commerce model satisfies emerging niche expectations, though scaling relies on micro-supply validation.",
        insights: [
          "Demand Insight: Extremely high search volume indicates strong organic consumer awareness for healthy pet food.",
          "Customer Insight: Pet parents seek organic-certified ingredients and direct home delivery convenience.",
          "Revenue Insight: Direct-to-consumer sales coupled with high margins support scaling operations.",
          "Competition Insight: Local shops exist but fail to provide specialized organic formulations.",
          "Growth Insight: Low cost of raw ingredient procurement supports strong early-stage unit economics."
        ],
        recommendation: "Build a prototype website and pitch first production batches directly to local vet clinics."
      }),
      market_analysis: JSON.stringify({
        insights: [
          "Search query density shows 25% year-on-year growth for organic pet products.",
          "Urban hubs in Telangana show expanding consumer query velocity.",
          "Pet humanization acts as a strong category macro-growth catalyst.",
          "Rising premium segment availability supports high initial pricing tiers."
        ],
        interpretation: "The Hyderabad pet care segment shows positive growth signals. Increasing query rates suggest that an early entrant focused on certified formulations can secure a durable local brand presence."
      }),
      competitor_analysis: JSON.stringify({
        competitors: [
          { name: "Pawsome Bites", rating: 4.8, reviews: 240, address: "Jubilee Hills, Hyderabad", differentiator: "Strong brand authority in dry kibble but lacks organic-certified product lines." },
          { name: "GreenNose Feeders", rating: 4.2, reviews: 84, address: "Gachibowli, Hyderabad", differentiator: "Eco-friendly branding with a moderate customer review rate, limited product customization." }
        ],
        gap_analysis: {
          premium_segment: "Organic-certified formulations are largely unavailable locally, leaving room for a premium product brand.",
          differentiation_potential: "Strong opportunity to differentiate through custom recipes and subscription meal kits.",
          market_saturation: "Moderate local competition, primarily focused on offline retail sales.",
          expansion_opportunity: "High potential to scale delivery routes to adjacent high-density residential hubs."
        }
      }),
      opportunity_analysis: JSON.stringify({
        strengths: [
          "Premium product margin levels.",
          "High customer lifetime value potential."
        ],
        opportunities: [
          "Subscription packaging meal kits.",
          "Partnership networks with veterinary clinics."
        ],
        key_opportunities: [
          "Develop a monthly recurring subscription pet meal plan.",
          "Partner with local boutique veterinarians for retail distribution.",
          "Host weekend pop-up brand awareness stands in dog parks.",
          "Implement personalized ingredient packages based on pet size.",
          "Collaborate with pet micro-influencers to lower brand acquisition costs."
        ],
        roadmap: [
          { phase: "Week 1–2", title: "Product Formulation", tasks: ["Source ingredients from organic suppliers", "Run first kitchen test batches with friends' dogs"] },
          { phase: "Week 3–4", title: "Waitlist Launch", tasks: ["Publish basic landing page with a waitlist form", "Launch local search campaigns"] },
          { phase: "Month 2", title: "Soft Launch", tasks: ["Fulfill first 50 waitlist subscriber orders", "Collect customer formulation feedback"] },
          { phase: "Month 3", title: "Subscription Rollout", tasks: ["Launch recurring billing website", "Scale marketing budget and hire packaging assistants"] }
        ]
      }),
      risk_analysis: JSON.stringify({
        weaknesses: [
          "Initial raw supply chain friction.",
          "High early logistics delivery overhead."
        ],
        threats: [
          "Aggressive price cuts by mass brands.",
          "Strict local licensing requirements."
        ],
        key_risks: [
          "Raw ingredient shelf-life stability.",
          "Underestimating customer acquisition costs."
        ]
      }),
      final_recommendation: JSON.stringify({
        potential: 5,
        confidence: 82,
        status: "🟢 Strong Opportunity",
        reasons: [
          "Strong local search trends show a growing market for pet care.",
          "Competitors focus on physical retail, leaving e-commerce open.",
          "Pet food has high repeat-purchase behavior, supporting subscription revenue."
        ],
        strengths: [
          "Certified organic brand positioning",
          "High repeat purchase behavior"
        ],
        risks: [
          "Raw supply chain ingredient shelf-life",
          "Customer acquisition cost volume inflation"
        ],
        next_step: "Order first small raw batch and launch the waitlist website."
      })
    },
    business_names: [
      { name: 'Pawganic.in', brand_uniqueness: 94, rationale: '• Connection to category: Direct pun on pet paws and organic formulations.\n• Emotional appeal: Welcoming and pure.\n• Brand perception: High-end quality care.\n• Market suitability: Fits urban audience seeking organic food.', why_recommended: "Pawganic.in stands out as the most memorable name with clear organic indicators and direct local relevance." },
      { name: 'NaturaPet.com', brand_uniqueness: 88, rationale: '• Connection to category: Focuses on natural pet nutrition.\n• Emotional appeal: Trustworthy and clean.\n• Brand perception: Premium product brand.\n• Market suitability: Great for e-commerce catalog.', why_recommended: "NaturaPet is a strong global-facing option but requires international shipping preparation." },
      { name: 'VitaPaws', brand_uniqueness: 80, rationale: '• Connection to category: Vitality and pet health.\n• Emotional appeal: Scientific and active.\n• Brand perception: Veterinary-grade products.\n• Market suitability: Fits pet subscription plans.', why_recommended: "VitaPaws is ideal if the brand shifts towards veterinary medical foods." }
    ],
    competitors: [
      { title: 'Pawsome Bites', rating: 4.8, reviews: 240, address: 'Jubilee Hills, Hyderabad' },
      { title: 'GreenNose Feeders', rating: 4.2, reviews: 84, address: 'Gachibowli, Hyderabad' }
    ],
    trends: [
      { date: 'Jan', value: 45 },
      { date: 'Feb', value: 52 },
      { date: 'Mar', value: 48 },
      { date: 'Apr', value: 61 },
      { date: 'May', value: 59 },
      { date: 'Jun', value: 75 },
      { date: 'Jul', value: 82 },
      { date: 'Aug', value: 80 },
      { date: 'Sep', value: 88 },
      { date: 'Oct', value: 95 },
      { date: 'Nov', value: 91 },
      { date: 'Dec', value: 100 }
    ]
  };

  const report = reportPayload || fallbackReport;
  const { metadata, scores, analysis, business_names, competitors, trends } = report;

  const [selectedTimeRange, setSelectedTimeRange] = useState('12M');
  const [isSaved, setIsSaved] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const downloadHtmlReport = (reportData) => {
    const { metadata, scores, analysis, business_names, competitors } = reportData;
    const category = getBusinessCategory(metadata?.idea_text);
    const parsedSummary = parseJSON(analysis?.executive_summary, {});
    const parsedMarket = parseJSON(analysis?.market_analysis, {});
    const parsedCompetitors = parseJSON(analysis?.competitor_analysis, {});
    const parsedOpportunity = parseJSON(analysis?.opportunity_analysis, {});
    const parsedRisk = parseJSON(analysis?.risk_analysis, {});
    const parsedVerdict = parseJSON(analysis?.final_recommendation, {});

    const htmlContent = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BizVision AI - Startup Intelligence Report</title>
    <style>
      body {
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
        line-height: 1.6;
        color: #0F172A;
        background-color: #FAFBFD;
        margin: 0;
        padding: 40px 20px;
      }
      .container {
        max-width: 900px;
        margin: 0 auto;
        background: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 24px;
        padding: 40px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.02);
      }
      .header {
        border-bottom: 2px solid #F1F5F9;
        padding-bottom: 30px;
        margin-bottom: 30px;
      }
      .title {
        font-size: 28px;
        font-weight: 800;
        color: #1E1B4B;
        margin: 0 0 10px 0;
      }
      .meta {
        font-size: 14px;
        color: #64748B;
        font-weight: 600;
      }
      .score-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 15px;
        margin-bottom: 30px;
      }
      .score-card {
        background: #F8FAFC;
        border: 1px solid #E2E8F0;
        border-radius: 12px;
        padding: 15px;
        text-align: center;
      }
      .score-label {
        font-size: 10px;
        font-weight: 700;
        color: #64748B;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        margin-bottom: 5px;
      }
      .score-value {
        font-size: 24px;
        font-weight: 800;
        color: #4F46E5;
      }
      .section {
        margin-bottom: 35px;
      }
      .section-title {
        font-size: 18px;
        font-weight: 700;
        color: #1E1B4B;
        border-left: 4px solid #4F46E5;
        padding-left: 12px;
        margin-bottom: 15px;
      }
      .card {
        background: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 16px;
        padding: 20px;
        margin-bottom: 15px;
      }
      .list-item {
        margin-bottom: 8px;
        font-size: 14px;
      }
      .bullet {
        color: #10B981;
        font-weight: bold;
        margin-right: 8px;
      }
      .badge {
        display: inline-block;
        padding: 4px 8px;
        font-size: 11px;
        font-weight: 700;
        border-radius: 6px;
        background: #EEF2FF;
        color: #4F46E5;
      }
      @media print {
        body { background: #FFFFFF; padding: 0; }
        .container { border: none; box-shadow: none; padding: 0; }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="badge">BIZVISION AI REPORT</div>
        <h1 class="title">"${metadata?.idea_text}"</h1>
        <div class="meta">
          📍 Location: ${metadata?.location || 'Global'} &nbsp;|&nbsp; 
          💼 Industry: ${metadata?.industry || category.label} &nbsp;|&nbsp;
          ⚙️ Type: ${metadata?.business_type || 'General'}
        </div>
      </div>

      <div class="score-grid">
        <div class="score-card">
          <div class="score-label">Health Score</div>
          <div class="score-value">${scores?.viability || 50}</div>
        </div>
        <div class="score-card">
          <div class="score-label">Demand Score</div>
          <div class="score-value">${scores?.demand || 50}</div>
        </div>
        <div class="score-card">
          <div class="score-label">Competition</div>
          <div class="score-value">${100 - (scores?.competition || 50)}</div>
        </div>
        <div class="score-card">
          <div class="score-label">Risk Rating</div>
          <div class="score-value">${100 - (scores?.risk || 50)}</div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">Executive Summary</div>
        <div class="card">
          <p>${parsedSummary.paragraph || "Analysis details are generated dynamically."}</p>
          <h4 style="margin-top: 15px; margin-bottom: 10px;">Key Insights:</h4>
          <div>
            ${(parsedSummary.insights || []).map(ins => `<div class="list-item"><span class="bullet">●</span> ${ins}</div>`).join('')}
          </div>
          <h4 style="margin-top: 15px; margin-bottom: 5px;">Strategic Recommendation:</h4>
          <p style="font-weight: 600; color: #4F46E5; margin: 0;">${parsedSummary.recommendation || "Initiate pilot."}</p>
        </div>
      </div>

      <div class="section">
        <div class="section-title">Market Intelligence</div>
        <div class="card">
          <p>${parsedMarket.interpretation || "Market data reflects stable interest patterns."}</p>
          <h4 style="margin-top: 15px; margin-bottom: 10px;">Key Observations:</h4>
          <div>
            ${(parsedMarket.insights || []).map(ins => `<div class="list-item"><span class="bullet">●</span> ${ins}</div>`).join('')}
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">Competitor Saturation</div>
        <div class="card">
          <h4 style="margin: 0 0 15px 0;">Identified Competitors:</h4>
          ${(parsedCompetitors.competitors || competitors || []).map(c => `
            <div style="margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid #F1F5F9;">
              <strong>${c.name || c.title}</strong> (${c.rating || 4.0}★)
              <p style="margin: 5px 0; font-size: 13px; color: #64748B;">${c.differentiator || "Local provider servicing traditional markets."}</p>
            </div>
          `).join('')}
        </div>
      </div>

      <div class="section">
        <div class="section-title">AI Brand Suggestions</div>
        <div class="card">
          ${(business_names || []).map(b => `
            <div style="margin-bottom: 15px;">
              <strong>${b.name}</strong> <span class="badge" style="font-size: 9px;">${b.brand_uniqueness}% Unique</span>
              <p style="margin: 5px 0; font-size: 13px; color: #475569;">${b.why_recommended || ""}</p>
            </div>
          `).join('')}
        </div>
      </div>

      <div class="section">
        <div class="section-title">Recommended Action Plan</div>
        <div class="card">
          ${(parsedOpportunity.roadmap || []).map(r => `
            <div style="margin-bottom: 15px;">
              <strong>${r.phase}: ${r.title}</strong>
              <ul style="margin: 5px 0; padding-left: 20px; font-size: 13px;">
                ${(r.tasks || []).map(t => `<li>${t}</li>`).join('')}
              </ul>
            </div>
          `).join('')}
        </div>
      </div>
    </div>
  </body>
  </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const fileName = (metadata?.idea_text || "Report")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    link.download = `bizvision-ai-${fileName || 'report'}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = useCallback(() => {
    window.print();
    downloadHtmlReport(report);
  }, [report]);

  const handleShare = useCallback(() => {
    const url = window.location.href;
    navigator.clipboard.writeText(url).then(() => {
      alert('Report link copied to clipboard!');
    });
  }, []);

  const handleSaveToWorkspace = useCallback(() => {
    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      setIsSaved(prev => !prev);
    }, 800);
  }, []);

  const handleTimeRangeChange = useCallback((range) => {
    setSelectedTimeRange(range);
  }, []);

  const handleGenerateBusinessPlan = useCallback(() => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      alert('AI Business Plan generation started! Check back shortly.');
    }, 2000);
  }, []);

  return (
    <div className="min-h-screen w-full bg-background flex flex-col relative font-sans text-foreground">
      <ReportHeader 
        isSaved={isSaved}
        onSave={handleSaveToWorkspace}
        onDownload={handleDownloadPDF}
        onShare={handleShare}
        isLoading={isLoading}
      />

      <main className="flex-1 w-full max-w-[1400px] mx-auto px-6 py-8 space-y-8 pb-32">
        
        {/* Venture Statement Callout */}
        <div className="p-8 rounded-[2rem] bg-gradient-to-r from-card to-card/50 border border-border/50 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-indigo-50 text-indigo-600 uppercase tracking-wider">
              <Icon icon="lucide:sparkles" /> Validated Venture Idea
            </span>
            <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-foreground">
              "{metadata?.idea_text || 'Startup Concept'}"
            </h1>
            <div className="flex items-center gap-4 text-xs font-semibold text-muted-foreground">
              <span className="flex items-center gap-1"><Icon icon="lucide:map-pin" className="text-sm text-indigo-600" /> {metadata?.location || 'Global'}</span>
              <span className="flex items-center gap-1"><Icon icon="lucide:briefcase" className="text-sm text-indigo-600" /> {metadata?.business_type || 'General'}</span>
            </div>
          </div>
          <div className="flex items-center gap-2 text-xs font-bold bg-emerald-50 text-emerald-600 border border-emerald-200 px-3.5 py-2 rounded-xl self-start md:self-center">
            <Icon icon="lucide:check-circle-2" className="text-sm text-emerald-500" /> AI Validated Pipeline
          </div>
        </div>

        {/* Business Health Overview */}
        <BusinessHealthOverview scores={scores} />

        {/* Executive Summary + Business Rating */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <ExecutiveSummary scores={scores} analysis={analysis} metadata={metadata} />
          <BusinessRatingCard score={scores?.viability || 50} confidence={scores?.viability || 50} />
        </div>

        {/* Market Intelligence + Chart */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <MarketIntelligenceChart 
              trends={trends}
              timeRange={selectedTimeRange} 
              onRangeChange={handleTimeRangeChange} 
            />
          </div>
          <MarketInsightsCard text={analysis?.market_analysis} scores={scores} trends={trends} />
        </div>

        {/* Competitor Intelligence */}
        <CompetitorIntelligence competitors={competitors} analysis={analysis} scores={scores} metadata={metadata} />

        {/* Demand & Revenue Potential */}
        <DemandRevenueAnalysis scores={scores} metadata={metadata} />

        {/* SWOT Analysis */}
        <SWOTAnalysis scores={scores} competitors={competitors} analysis={analysis} metadata={metadata} />

        {/* Key Opportunities */}
        <KeyOpportunities text={analysis?.opportunity_analysis} analysis={analysis} metadata={metadata} />

        {/* Recommended Action Plan */}
        <RecommendedActionPlan scores={scores} analysis={analysis} metadata={metadata} />

        {/* AI Brand Name Suggestions */}
        <BrandNameRationale businessNames={business_names} metadata={metadata} />

        {/* Final Verdict */}
        <FinalVerdict 
          scores={scores}
          analysis={analysis}
          onGenerate={handleGenerateBusinessPlan} 
          onSave={handleSaveToWorkspace}
          isLoading={isGenerating}
          metadata={metadata}
        />

      </main>

      {/* Mobile Action Bar */}
      <div className="md:hidden fixed bottom-0 left-0 right-0 bg-background/80 backdrop-blur-lg border-t border-border p-4 flex gap-3 z-40">
        <button onClick={handleDownloadPDF} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl bg-muted font-bold text-sm">
          <Icon icon="lucide:download" /> PDF
        </button>
        <button onClick={handleShare} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-xl bg-muted font-bold text-sm">
          <Icon icon="lucide:share-2" /> Share
        </button>
      </div>
    </div>
  );
};

export default IntelligenceReport;
