import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Icon } from '@iconify/react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  Filler
} from 'chart.js';
import { Line, Bar } from 'react-chartjs-2';
import gsap from 'gsap';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

import html2pdf from 'html2pdf.js';

const loadHtml2Pdf = () => {
  return Promise.resolve(html2pdf);
};

const formatCurrencyToINR = (val) => {
  if (!val) return "N/A";
  let str = String(val).trim();
  
  // If it already has Indian Rupee symbol, return it
  if (str.includes('₹')) {
    return str;
  }
  
  // Convert K/k or M/m suffixes
  str = str.replace(/\$(\d+(?:\.\d+)?)\s*[kK]\b/g, (m, p1) => `$${parseFloat(p1) * 1000}`);
  str = str.replace(/\$(\d+(?:\.\d+)?)\s*[mM]\b/g, (m, p1) => `$${parseFloat(p1) * 1000000}`);
  
  // If no currency symbols but has digits, add $ prefix to trigger conversion
  if (!str.includes('$') && /^\d/.test(str)) {
    str = str.replace(/(\b\d[\d,]*\b)/g, '$$$1');
  }
  
  // Convert USD to INR
  str = str.replace(/\$([\d,]+(?:\.\d+)?)/g, (match, p1) => {
    const num = parseFloat(p1.replace(/,/g, ''));
    if (!isNaN(num)) {
      const inrValue = num * 83;
      return '₹' + Math.round(inrValue).toLocaleString('en-IN');
    }
    return '₹' + p1;
  });
  
  str = str.replace(/\$/g, '₹');
  return str;
};

const CircularGauge = ({ label, value, ringColor, bgColor }) => {
  const [displayValue, setDisplayValue] = useState(0);
  const ringRef = useRef(null);
  
  const radius = 28;
  const circumference = 2 * Math.PI * radius;

  useEffect(() => {
    const obj = { val: 0 };
    // Animating number count up
    gsap.to(obj, {
      val: value,
      duration: 1.5,
      ease: 'power2.out',
      onUpdate: () => {
        setDisplayValue(Math.round(obj.val));
      }
    });

    // Animating circle drawing
    if (ringRef.current) {
      const targetOffset = circumference - (value / 100) * circumference;
      gsap.fromTo(ringRef.current, 
        { strokeDashoffset: circumference },
        { strokeDashoffset: targetOffset, duration: 1.5, ease: 'power2.out' }
      );
    }
  }, [value, circumference]);

  return (
    <motion.div
      whileHover={{ scale: 1.03, y: -2 }}
      className={cn("bg-slate-50/40 border border-slate-100 rounded-2xl p-5 flex flex-col items-center justify-center text-center space-y-3.5 shadow-sm transition-all duration-300", bgColor)}
    >
      <div className="relative flex items-center justify-center w-16 h-16">
        <svg className="w-16 h-16 transform -rotate-90">
          <circle cx="32" cy="32" r={radius} className="text-slate-100" strokeWidth="4.5" stroke="currentColor" fill="transparent" />
          <circle 
            ref={ringRef}
            cx="32" 
            cy="32" 
            r={radius} 
            className={`${ringColor} transition-all`} 
            strokeWidth="5" 
            strokeDasharray={circumference} 
            strokeLinecap="round" 
            stroke="currentColor" 
            fill="transparent" 
          />
        </svg>
        <span className="absolute text-sm font-extrabold text-slate-800">{displayValue}%</span>
      </div>
      <span className="text-xs font-bold uppercase tracking-wider text-slate-500 leading-tight">{label}</span>
    </motion.div>
  );
};

const AnimatedViabilityValue = ({ value }) => {
  const [displayValue, setDisplayValue] = useState(0);
  useEffect(() => {
    const obj = { val: 0 };
    gsap.to(obj, {
      val: value,
      duration: 1.5,
      ease: 'power2.out',
      onUpdate: () => {
        setDisplayValue(Math.round(obj.val));
      }
    });
  }, [value]);
  return <p className="text-3xl font-extrabold">{displayValue}%</p>;
};

const DisclaimerBanner = () => (
  <div className="p-4 rounded-xl bg-indigo-50/40 border border-indigo-100/50 text-indigo-800 text-xs font-semibold leading-relaxed flex items-center gap-3 shadow-sm select-none">
    <Icon icon="lucide:alert-circle" className="text-lg text-indigo-600 flex-shrink-0" />
    <span className="text-left">
      <strong>Transparency Disclaimer:</strong> This feasibility report is generated by AI for preliminary idea validation and market estimation. 
      All financial projections, ratings, and recommendations should be audited by local financial and licensing experts before starting operations.
    </span>
  </div>
);

// ─── HEADER COMPONENT ───────────────────────────────────────────────────────
const ReportHeader = ({ isSaved, onSave, onDownload, isLoading }) => (
  <header className="sticky top-0 z-50 w-full bg-[#FAFBFD]/90 backdrop-blur-xl border-b border-slate-200/80 shadow-sm">
    <div className="max-w-[1400px] mx-auto px-6 h-16 flex items-center justify-between">
      <div className="flex items-center gap-4">
        <Link to="/history-dashboard" className="flex items-center justify-center w-8 h-8 rounded-full hover:bg-muted text-foreground transition-colors">
          <Icon icon="lucide:arrow-left" className="text-xl" />
        </Link>
        <div className="h-4 w-px bg-border"></div>
        <div className="flex flex-col">
          <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Decision Engine Report</span>
          <span className="text-sm font-bold text-indigo-600 mt-0.5">BizVision AI</span>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <button 
          onClick={onDownload}
          className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-muted text-sm font-medium transition-colors cursor-pointer"
        >
          <Icon icon="lucide:download" className="text-indigo-600" /> Export PDF
        </button>
        <button 
          onClick={onSave}
          disabled={isLoading}
          className={cn(
            "flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-semibold shadow-sm transition-all cursor-pointer",
            isSaved 
              ? "bg-emerald-50 text-emerald-600 border border-emerald-200" 
              : "bg-indigo-600 text-white hover:bg-indigo-700"
          )}
        >
          <Icon icon={isSaved ? "lucide:check" : "lucide:save"} />
          {isLoading ? "Saving..." : isSaved ? "Saved" : "Save to Workspace"}
        </button>
      </div>
    </div>
  </header>
);

// ─── RADIAL GAUGE FOR INVESTMENT READINESS ─────────────────────────────────
const InvestmentReadinessGauge = ({ recommendation }) => {
  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50 flex flex-col items-center justify-center min-h-[360px] text-center">
      <div className="w-16 h-16 rounded-2xl bg-indigo-50 flex items-center justify-center mb-6">
        <Icon icon="lucide:shield-check" className="text-3xl text-indigo-600" />
      </div>
      <h3 className="text-lg font-extrabold text-slate-800 mb-2">Investment Readiness</h3>
      <p className="text-xs text-muted-foreground uppercase font-bold tracking-wider mb-4">VC Strategic Recommendation</p>
      <div className="px-4">
        <p className="text-sm leading-relaxed text-slate-600 font-semibold bg-slate-50/50 p-4 rounded-xl border border-slate-100/50">
          "{recommendation}"
        </p>
      </div>
    </div>
  );
};

// ─── SCENARIO PROJECTIONS & STARTUP COSTS ──────────────────────────────────
const FinancialSizingSection = ({ revenue, costs }) => {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      {/* Startup Cost Engine */}
      <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
            <Icon icon="lucide:calculator" className="text-xl text-indigo-600" />
          </div>
          <div>
            <h3 className="text-lg font-bold tracking-tight">Startup Cost Breakdown</h3>
            <p className="text-sm text-muted-foreground font-medium">Location-aware capitalization tiers</p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 text-center">
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block mb-1">Minimum Launch</span>
            <span className="text-lg font-extrabold text-slate-700">{formatCurrencyToINR(costs?.minimum_cost || "₹5,00,000")}</span>
          </div>
          <div className="p-4 bg-indigo-50/50 rounded-xl border border-indigo-100 text-center">
            <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Recommended MVP</span>
            <span className="text-lg font-extrabold text-indigo-700">{formatCurrencyToINR(costs?.recommended_cost || "₹15,00,000")}</span>
          </div>
          <div className="p-4 bg-cyan-50/50 rounded-xl border border-cyan-100 text-center">
            <span className="text-[10px] font-bold text-cyan-600 uppercase tracking-wider block mb-1">Premium Launch</span>
            <span className="text-lg font-extrabold text-cyan-700">{formatCurrencyToINR(costs?.premium_launch_cost || "₹25,00,000")}</span>
          </div>
        </div>

        <div className="mt-6 pt-6 border-t border-border/50 space-y-2 text-xs text-muted-foreground leading-relaxed font-medium">
          <p>• Costs encompass local commercial lease deposits, standard fit-outs, early payroll, local licenses, and marketing.</p>
          <p>• Estimated values are resolved based on the target locality pricing indices.</p>
        </div>
      </div>

      {/* Revenue Potential Engine */}
      <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center">
            <Icon icon="lucide:dollar-sign" className="text-xl text-cyan-600" />
          </div>
          <div>
            <h3 className="text-lg font-bold tracking-tight">Revenue Scenario Modeling</h3>
            <p className="text-sm text-muted-foreground font-medium">Conservative, expected, and aggressive cases</p>
          </div>
        </div>

        <div className="space-y-3.5 mb-6">
          <div className="flex justify-between items-center p-3 rounded-lg bg-slate-50 border border-slate-100">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Conservative Scenario (Low Case)</span>
            <span className="text-sm font-extrabold text-slate-700">{formatCurrencyToINR(revenue?.low_case || "₹2,50,000 /mo")}</span>
          </div>
          <div className="flex justify-between items-center p-3 rounded-lg bg-indigo-50/40 border border-indigo-100">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider">Target Objective (Expected Case)</span>
            <span className="text-sm font-extrabold text-indigo-700">{formatCurrencyToINR(revenue?.expected_case || "₹8,00,000 /mo")}</span>
          </div>
          <div className="flex justify-between items-center p-3 rounded-lg bg-emerald-50/40 border border-emerald-100">
            <span className="text-xs font-bold text-emerald-600 uppercase tracking-wider">Aggressive Objective (High Case)</span>
            <span className="text-sm font-extrabold text-emerald-700">{formatCurrencyToINR(revenue?.high_case || "₹20,00,000 /mo")}</span>
          </div>
        </div>

        <div>
          <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider block mb-2">Model Assumptions</span>
          <ul className="space-y-1.5">
            {(revenue?.assumptions || ["Based on local pricing metrics and standard buyer conversions."]).map((asm, i) => (
              <li key={i} className="text-xs text-muted-foreground leading-normal flex gap-2 font-medium">
                <span className="text-emerald-500 font-bold">•</span>
                <span>{asm}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};

// ─── SWOT ANALYSIS QUADRANT ────────────────────────────────────────────────
const SWOTAnalysisSection = ({ swot }) => {
  const quadrants = [
    { title: "Strengths", items: swot?.strengths, icon: "lucide:zap", bg: "bg-emerald-50/30 hover:bg-emerald-50/55 border-emerald-100/60 text-emerald-800" },
    { title: "Weaknesses", items: swot?.weaknesses, icon: "lucide:alert-circle", bg: "bg-amber-50/30 hover:bg-amber-50/55 border-amber-100/60 text-amber-800" },
    { title: "Opportunities", items: swot?.opportunities, icon: "lucide:lightbulb", bg: "bg-indigo-50/30 hover:bg-indigo-50/55 border-indigo-100/60 text-indigo-800" },
    { title: "Threats", items: swot?.threats, icon: "lucide:shield-alert", bg: "bg-red-50/30 hover:bg-red-50/55 border-red-100/60 text-red-800" }
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
      {quadrants.map((q, idx) => (
        <motion.div
          key={idx}
          whileHover={{ y: -4, scale: 1.01 }}
          className={cn("p-5 rounded-2xl border bg-gradient-to-br transition-all duration-300 shadow-sm", q.bg)}
        >
          <div className="flex items-center gap-2.5 mb-3.5 pb-2 border-b border-current/10">
            <Icon icon={q.icon} className="text-xl" />
            <h4 className="font-extrabold text-sm uppercase tracking-wider">{q.title}</h4>
          </div>
          <ul className="space-y-2.5">
            {(q.items || ["Insufficient evidence available."]).map((item, i) => (
              <li key={i} className="text-xs leading-relaxed flex gap-2 font-semibold">
                <span className="font-bold">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </motion.div>
      ))}
    </div>
  );
};

// ─── LAUNCH ROADMAP ROAD TIMELINE ──────────────────────────────────────────
const LaunchRoadmapSection = ({ roadmap }) => {
  const steps = [
    { label: "Day 1 to 30", title: "Operational Sourcing", tasks: roadmap?.first_30_days || ["Identify raw supplier loops", "Publish first waitlist model"] },
    { label: "Day 31 to 60", title: "Pilot Activation", tasks: roadmap?.days_31_to_60 || ["Bootstrap subscription dashboards", "Run trial product soft launch"] },
    { label: "Day 61 to 90", title: "Acquisition scaling", tasks: roadmap?.days_61_to_90 || ["Deploy targeted marketing push", "Stabilize packaging workflows"] }
  ];

  return (
    <div className="bg-card rounded-[2rem] p-8 shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-border/50">
      <h3 className="text-lg font-bold text-foreground mb-6">Launch Roadmap & Milestones</h3>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {steps.map((step, idx) => (
          <div key={idx} className="relative p-5 rounded-xl border border-indigo-100 bg-indigo-50/15">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider block mb-1">{step.label}</span>
            <h4 className="text-sm font-extrabold text-foreground mb-3">{step.title}</h4>
            <ul className="space-y-2">
              {step.tasks.map((task, t) => (
                <li key={t} className="text-xs text-muted-foreground leading-normal flex gap-2 font-medium">
                  <span className="text-emerald-500 font-bold">•</span>
                  <span>{task}</span>
                </li>
              ))}
            </ul>
            {idx < steps.length - 1 && (
              <div className="hidden lg:flex absolute -right-3 top-1/2 transform -translate-y-1/2 text-indigo-300 z-10">
                <Icon icon="lucide:arrow-right" className="text-xl" />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── COMPETITORS RATINGS COMPARISON BAR CHART ──────────────────────────────
const CompetitorsRatingsChart = ({ competitors }) => {
  const cleanCompetitorName = (name) => {
    if (!name) return 'Competitor';
    let clean = name.split(/[|\[\(\-,]/)[0].trim();
    clean = clean.replace(/\b(pet store & spa|pet store|pet shop|veterinary hospital|veterinary clinic|restaurant & bar|restaurant|cafe|café|lounge|dhaba|bistro|diner|kitchen)\b/gi, '').trim();
    if (clean.length > 22) {
      clean = clean.slice(0, 20) + '...';
    }
    return clean || 'Competitor';
  };

  const labels = competitors.map(c => cleanCompetitorName(c.name || c.title));
  const ratings = competitors.map(c => Number(c.rating) || 4.0);

  const data = {
    labels: labels.slice(0, 5),
    datasets: [
      {
        label: 'Competitor Rating',
        data: ratings.slice(0, 5),
        backgroundColor: 'rgba(99, 102, 241, 0.75)',
        borderColor: '#6366F1',
        borderWidth: 2,
        borderRadius: 6,
        barThickness: 16,
      }
    ]
  };

  const options = {
    indexAxis: 'y',
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: '#0F172A',
        padding: 12,
        titleFont: { family: 'Inter', size: 12 },
        bodyFont: { family: 'Inter', size: 13, weight: 'bold' },
        cornerRadius: 6,
      }
    },
    scales: {
      x: { min: 0, max: 5, ticks: { stepSize: 1, font: { family: 'Inter', size: 10 } } },
      y: { grid: { display: false }, ticks: { font: { family: 'Inter', size: 10 } } }
    }
  };

  return (
    <div className="h-64 w-full relative">
      <Bar data={data} options={options} />
    </div>
  );
};

// ─── MAIN REPORT VIEW ───────────────────────────────────────────────────────
const IntelligenceReport = () => {
  const location = useLocation();
  const reportPayload = location.state?.report;

  // Premium offline default fallback data
  const fallbackReport = {
    metadata: {
      idea_text: 'Subscription organic pet food',
      location: 'Hyderabad, India',
      business_type: 'Direct-to-Consumer (D2C)',
      industry: 'Pet Nutrition'
    },
    report: {
      executive_summary: {
        title: "Pawganic Sourcing",
        business_summary: "Certified organic daily meal plans for urban dogs with direct home delivery.",
        one_paragraph_verdict: "High viability target opportunity. Establishing direct cold-chain logistics loops with poultry farms in Telangana is essential.",
        key_opportunity: "Absence of certified local organic pet food suppliers with customized daily delivery options.",
        biggest_challenge: "Cold-chain logistics consistency and raw ingredient shelf-life limits."
      },
      market_overview: {
        search_demand: "Search velocity for organic formulations reflects expanding momentum (25% growth) in high-income Telangana residential sectors.",
        trend_direction: "Strong upward momentum projected over the next 18 months, driven by pet humanization macros.",
        market_maturity: "Emerging local niche with low competitor density."
      },
      competitor_intelligence: {
        market_gaps: "Lack of certified organic validation and poor e-commerce subscription personalization from traditional providers."
      },
      customer_intelligence: {
        customer_persona: "High-income pet owners who treat pets as family members, prioritizing premium nutrition.",
        pain_points: ["Digestive sensitivities", "Chemical additives", "Inconsistent fresh supply"],
        buying_behavior: "Vet recommendation and subscription convenience.",
        spending_patterns: "Average spend of ₹2,50,000/pet monthly, low price sensitivity."
      },
      industry_trends: {
        news_analysis: "Growing regulatory focus on pet food grade labeling and consumer shift to natural alternatives.",
        trend_analysis: "Transition from dry kibble to fresh-frozen high-moisture diets.",
        emerging_changes: "Increasing adoption of direct-to-door subscription boxes."
      },
      opportunity_analysis: {
        why_work: "High pet owner density in Jubilee Hills combined with premium purchasing power.",
        untapped_opportunities: ["Custom allergen-free subscription kits", "Vet clinic co-branding"],
        premium_positioning: "Direct-to-consumer premium organic label with cold-chain provenance mapping."
      },
      revenue_model: {
        revenue_streams: ["Monthly subscription boxes", "A-la-carte specialty treats"],
        upsells: "Allergen testing kit, specialized veterinary-grade health supplements.",
        memberships: "VIP club offering free vet consult calls and priority delivery routes.",
        subscriptions: "Weekly, bi-weekly, or monthly recurring subscription tiers."
      },
      cost_capital_analysis: {
        estimated_startup_cost: "₹5,00,000",
        operating_cost: "₹1,20,000 /mo",
        recommended_capital: "₹12,00,000",
        runway: "9-12 Months",
        context_text: "Encompasses kitchen lease, vacuum packaging lines, raw organic sourcing deposits, and initial local delivery fleet."
      },
      swot_analysis: {
        strengths: ["First-mover organic brand", "High-margin subscription model"],
        weaknesses: ["Cold-chain supply storage requirements", "High client acquisition cost"],
        opportunities: ["Local vet clinic partnerships", "Expanding to neighboring cities"],
        threats: ["Raw ingredient shelf-life limits", "Price war from commercial brands"]
      },
      risk_analysis: {
        risk_level: "Medium",
        top_risks: ["Supply chain shelf-life consistency", "Ingredient cost inflation"],
        mitigation_strategies: ["Automate delivery logs", "Implement vacuum storage lines", "Advance deposit billing"]
      },
      risk_assessment: {
        market_risks: "Slowing pet adoption rates post-pandemic.",
        competition_risks: "Commercial brands launching organic sub-brands.",
        operational_risks: "Cold chain log disruptions causing spoilage.",
        legal_risks: "Local health authority compliance and food safety inspections."
      },
      scenario_planning: {
        best_case: "₹20,00,000 /mo",
        expected_case: "₹8,00,000 /mo",
        worst_case: "₹2,50,000 /mo"
      },
      launch_roadmap: {
        week_1_2: ["Source ingredients from organic suppliers", "Run kitchen tests"],
        week_3_4: ["Launch waitlist landing page", "Setup subscription billing"],
        month_2: ["Initiate soft launch (50 orders)", "Secure initial clinic partnerships"],
        month_3: ["Gather customer feedback", "Scale social ads budget"]
      },
      founder_decision_engine: {
        market_fit: 88,
        competition: 74,
        scalability: 91,
        capital_efficiency: 79,
        risk: 67
      },
      final_verdict: {
        context_text: "Highly viable opportunity. Build local landing page waitlist first to validate customer acquisition cost before capital deployment.",
        investment_grade: "A",
        launch_recommendation: "Pilot First",
        confidence_level: "High"
      }
    },
    competitors: [
      { title: 'Pawsome Bites', rating: 4.8, reviews: 240, address: 'Jubilee Hills, Hyderabad' },
      { title: 'GreenNose Feeders', rating: 4.2, reviews: 84, address: 'Gachibowli, Hyderabad' }
    ],
    trends: [
      { date: 'Jan', value: 45 },
      { date: 'Feb', value: 52 },
      { date: 'Mar', value: 48 },
      { date: 'Apr', value: 61 },
      { date: 'May', value: 59 },
      { date: 'Jun', value: 75 },
      { date: 'Jul', value: 82 },
      { date: 'Aug', value: 80 },
      { date: 'Sep', value: 88 },
      { date: 'Oct', value: 95 },
      { date: 'Nov', value: 91 },
      { date: 'Dec', value: 100 }
    ]
  };

  const report = reportPayload || fallbackReport;
  const isRealReport = !!reportPayload;
  
  // Pivot access nodes
  const data = isRealReport ? report.report : fallbackReport.report;
  const metadata = report.metadata;
  const displayBusinessType = (() => {
    const type = metadata?.business_type || 'General';
    const ideaLower = (metadata?.idea_text || '').toLowerCase();
    const typeLower = type.toLowerCase();
    
    if (typeLower.includes('brick') || typeLower === 'general' || typeLower === 'general service' || typeLower === 'general business') {
      if (["restaurant", "cafe", "café", "kitchen", "bakery", "dining", "dhaba", "food", "veg", "vegetarian", "biryani", "meals", "tiffin"].some(w => ideaLower.includes(w))) {
        return "Restaurant / Dining";
      }
      if (["hotel", "resort", "lodge", "stay", "accommodation", "hostel", "inn"].some(w => ideaLower.includes(w))) {
        return "Hotel / Lodging";
      }
      if (["gym", "fitness", "yoga", "crossfit", "workout", "studio", "health club"].some(w => ideaLower.includes(w))) {
        return "Fitness Center / Gym";
      }
      if (["saas", "software", "dashboard", "app", "platform", "billing"].some(w => ideaLower.includes(w))) {
        return "SaaS / Software Product";
      }
    }
    return type;
  })();
  const competitors = report.competitors || [];
  const trends = report.trends || [];
  const news = report.news || [];
  const shopping = report.shopping || [];

  const [selectedTimeRange, setSelectedTimeRange] = useState('12M');
  const [isSaved, setIsSaved] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const reportRef = useRef(null);

  useEffect(() => {
    if (reportRef.current) {
      const cards = reportRef.current.querySelectorAll('.rounded-\\[2rem\\]');
      gsap.set(cards, { opacity: 0, y: 35 });
      gsap.to(cards, {
        opacity: 1,
        y: 0,
        duration: 0.8,
        stagger: 0.12,
        ease: 'power2.out',
        clearProps: 'transform,opacity',
        delay: 0.15
      });
    }
  }, []);

  const downloadHtmlReport = (reportData) => {
    const { metadata, report: rData, competitors: comps, trends: trendData, news: newsData, shopping: shopData } = reportData;
    const currentData = rData || fallbackReport.report;
    const category = metadata?.idea_text || "Startup Concept";

    const getListItems = (arr) => {
      if (!arr || !Array.isArray(arr)) return '<div class="text-muted">None specified</div>';
      return arr.map(item => `<div class="list-item"><span class="bullet">●</span> ${item}</div>`).join('');
    };

    const htmlContent = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BizVision AI - Premium Intelligence Report</title>
    <style>
      body {
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
        line-height: 1.6;
        color: #1E293B;
        background-color: #F8FAFC;
        margin: 0;
        padding: 40px 20px;
      }
      .container {
        max-width: 900px;
        margin: 0 auto;
        background: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 24px;
        padding: 45px;
        box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.03), 0 8px 10px -6px rgba(0, 0, 0, 0.03);
      }
      .header {
        border-bottom: 2px solid #F1F5F9;
        padding-bottom: 30px;
        margin-bottom: 35px;
        position: relative;
      }
      .badge-validated {
        position: absolute;
        top: 0;
        right: 0;
        background: #ECFDF5;
        border: 1px solid #A7F3D0;
        color: #065F46;
        padding: 6px 12px;
        font-size: 11px;
        font-weight: 700;
        border-radius: 12px;
        text-transform: uppercase;
        letter-spacing: 0.05em;
      }
      .title {
        font-size: 32px;
        font-weight: 800;
        color: #1E1B4B;
        margin: 0 0 12px 0;
      }
      .meta {
        font-size: 13px;
        color: #64748B;
        font-weight: 600;
        display: flex;
        gap: 15px;
        flex-wrap: wrap;
      }
      .section-card {
        background: #FFFFFF;
        border: 1px solid #E2E8F0;
        border-radius: 20px;
        padding: 24px;
        margin-bottom: 25px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.02);
      }
      .section-tag {
        font-size: 10px;
        font-weight: 800;
        color: #4F46E5;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        margin-bottom: 8px;
        display: inline-block;
        background: #EEF2FF;
        padding: 3px 8px;
        border-radius: 6px;
      }
      .section-title {
        font-size: 18px;
        font-weight: 800;
        color: #1E1B4B;
        margin: 0 0 16px 0;
        border-bottom: 1px solid #F1F5F9;
        padding-bottom: 8px;
      }
      .content-block {
        margin-bottom: 15px;
      }
      .content-label {
        font-size: 11px;
        font-weight: 700;
        color: #64748B;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        margin-bottom: 4px;
      }
      .content-text {
        font-size: 14px;
        color: #334155;
        margin: 0;
      }
      .list-item {
        margin-bottom: 8px;
        font-size: 14px;
        color: #334155;
        display: flex;
        align-items: center;
      }
      .bullet {
        color: #10B981;
        font-weight: bold;
        margin-right: 8px;
      }
      .grid-3 {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 15px;
        margin-top: 10px;
      }
      .grid-2 {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        margin-top: 10px;
      }
      .grid-card {
        background: #F8FAFC;
        border: 1px solid #E2E8F0;
        border-radius: 12px;
        padding: 15px;
      }
      .score-bar-container {
        margin-bottom: 14px;
      }
      .score-bar-header {
        display: flex;
        justify-content: space-between;
        font-size: 12px;
        font-weight: 700;
        color: #475569;
        margin-bottom: 5px;
      }
      .score-bar-bg {
        background: #E2E8F0;
        height: 8px;
        border-radius: 4px;
        overflow: hidden;
      }
      .score-bar-fill {
        background: #4F46E5;
        height: 100%;
        border-radius: 4px;
      }
      .verdict-card {
        background: linear-gradient(135deg, #1E1B4B 0%, #312E81 100%);
        color: #FFFFFF;
        border: none;
      }
      .verdict-card .section-tag {
        background: rgba(255,255,255,0.15);
        color: #FFFFFF;
      }
      .verdict-card .section-title {
        color: #FFFFFF;
        border-bottom: 1px solid rgba(255,255,255,0.1);
      }
      .verdict-value {
        font-size: 28px;
        font-weight: 900;
        color: #10B981;
        margin: 5px 0;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="badge-validated">VC Validated</div>
        <h1 class="title">${currentData.executive_summary?.title || category}</h1>
        <div class="meta">
          <span>📍 <strong>Location:</strong> ${metadata?.location || 'Global'}</span>
          <span>💼 <strong>Industry:</strong> ${metadata?.industry || 'General'}</span>
          <span>🏢 <strong>Model:</strong> ${metadata?.business_type || 'General'}</span>
        </div>
      </div>

      <!-- Executive Summary -->
      <div class="section-card">
        <h2 class="section-title">Executive Summary</h2>
        <div class="content-block">
          <div class="content-label">Business Summary</div>
          <p class="content-text">${currentData.executive_summary?.business_summary || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">One Paragraph Verdict</div>
          <p class="content-text">${currentData.executive_summary?.one_paragraph_verdict || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Key Opportunity</div>
          <p class="content-text">${currentData.executive_summary?.key_opportunity || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Biggest Challenge</div>
          <p class="content-text">${currentData.executive_summary?.biggest_challenge || "N/A"}</p>
        </div>
      </div>

      <!-- Market Overview -->
      <div class="section-card">
        <h2 class="section-title">Market Overview</h2>
        <div class="content-block">
          <div class="content-label">Search Demand</div>
          <p class="content-text">${currentData.market_overview?.search_demand || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Trend Direction</div>
          <p class="content-text">${currentData.market_overview?.trend_direction || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Market Maturity</div>
          <p class="content-text">${currentData.market_overview?.market_maturity || "N/A"}</p>
        </div>
      </div>

      <!-- Competitor Intelligence -->
      <div class="section-card">
        <h2 class="section-title">Competitor Intelligence</h2>
        <div class="content-block">
          <div class="content-label">Market Gaps & Vulnerabilities</div>
          <p class="content-text">${currentData.competitor_intelligence?.market_gaps || "N/A"}</p>
        </div>
        <div class="content-block" style="margin-top: 15px;">
          <div class="content-label">Identified Local Competitors</div>
          ${(comps || []).slice(0, 5).map(c => `
            <div style="margin-bottom: 12px; padding: 10px; background: #F8FAFC; border-radius: 8px; border: 1px solid #E2E8F0;">
              <strong>${c.title || c.name}</strong> - ${c.rating || '4.0'}★ (${c.reviews || 0} reviews)
              <div style="font-size: 12px; color: #64748B; margin-top: 3px;">📍 ${c.address || 'Address not listed'}</div>
            </div>
          `).join('')}
        </div>
      </div>

      <!-- Customer Intelligence -->
      <div class="section-card">
        <h2 class="section-title">Customer Intelligence</h2>
        <div class="content-block">
          <div class="content-label">Core Target Persona</div>
          <p class="content-text">${currentData.customer_intelligence?.customer_persona || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Observed Pain Points</div>
          ${getListItems(currentData.customer_intelligence?.pain_points)}
        </div>
        <div class="content-block">
          <div class="content-label">Buying Behavior</div>
          <p class="content-text">${currentData.customer_intelligence?.buying_behavior || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Spending Patterns</div>
          <p class="content-text">${currentData.customer_intelligence?.spending_patterns || "N/A"}</p>
        </div>
      </div>

      <!-- Industry Trends -->
      <div class="section-card">
        <h2 class="section-title">Industry Trends</h2>
        <div class="content-block">
          <div class="content-label">News Sentiment Analysis</div>
          <p class="content-text">${currentData.industry_trends?.news_analysis || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Trend Analysis</div>
          <p class="content-text">${currentData.industry_trends?.trend_analysis || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Emerging Regulatory or Market Changes</div>
          <p class="content-text">${currentData.industry_trends?.emerging_changes || "N/A"}</p>
        </div>
      </div>

      <!-- Opportunity Analysis -->
      <div class="section-card">
        <h2 class="section-title">Opportunity Analysis</h2>
        <div class="content-block">
          <div class="content-label">Why This Business May Work</div>
          <p class="content-text">${currentData.opportunity_analysis?.why_work || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Untapped Local Opportunities</div>
          ${getListItems(currentData.opportunity_analysis?.untapped_opportunities)}
        </div>
        <div class="content-block">
          <div class="content-label">Premium Positioning Hook</div>
          <p class="content-text">${currentData.opportunity_analysis?.premium_positioning || "N/A"}</p>
        </div>
      </div>

      <!-- Revenue Model -->
      <div class="section-card">
        <h2 class="section-title">Revenue Model</h2>
        <div class="content-block">
          <div class="content-label">Revenue Streams</div>
          ${getListItems(currentData.revenue_model?.revenue_streams)}
        </div>
        <div class="content-block">
          <div class="content-label">Upsell Opportunities</div>
          <p class="content-text">${currentData.revenue_model?.upsells || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Memberships Mechanics</div>
          <p class="content-text">${currentData.revenue_model?.memberships || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Subscription Tiering</div>
          <p class="content-text">${currentData.revenue_model?.subscriptions || "N/A"}</p>
        </div>
      </div>

      <!-- Financial & Scenario Analysis -->
      <div class="section-card">
        <h2 class="section-title">Financial & Scenario Analysis</h2>
        <div class="content-block">
          <div class="content-label" style="margin-bottom: 8px;">Cost & Capital Analysis</div>
          <div class="grid-3">
            <div class="grid-card">
              <div class="content-label">Startup Capital</div>
              <strong style="color: #4F46E5; font-size: 16px;">${formatCurrencyToINR(currentData.cost_capital_analysis?.estimated_startup_cost || "N/A")}</strong>
            </div>
            <div class="grid-card">
              <div class="content-label">Operating Cost</div>
              <strong style="color: #4F46E5; font-size: 16px;">${formatCurrencyToINR(currentData.cost_capital_analysis?.operating_cost || "N/A")}</strong>
            </div>
            <div class="grid-card">
              <div class="content-label">Recommended Capital</div>
              <strong style="color: #4F46E5; font-size: 16px;">${formatCurrencyToINR(currentData.cost_capital_analysis?.recommended_capital || "N/A")}</strong>
            </div>
          </div>
        </div>

        <div class="content-block" style="margin-top: 20px;">
          <div class="content-label" style="margin-bottom: 8px;">Scenario Planning</div>
          <div class="grid-3">
            <div class="grid-card">
              <div class="content-label">Best Case Scenario</div>
              <p class="content-text" style="font-weight: bold; margin-top: 5px;">${formatCurrencyToINR(currentData.scenario_planning?.best_case || "N/A")}</p>
            </div>
            <div class="grid-card">
              <div class="content-label">Expected Case Scenario</div>
              <p class="content-text" style="font-weight: bold; margin-top: 5px;">${formatCurrencyToINR(currentData.scenario_planning?.expected_case || "N/A")}</p>
            </div>
            <div class="grid-card">
              <div class="content-label">Worst Case Scenario</div>
              <p class="content-text" style="font-weight: bold; margin-top: 5px;">${formatCurrencyToINR(currentData.scenario_planning?.worst_case || "N/A")}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- SWOT Analysis -->
      <div class="section-card">
        <h2 class="section-title">SWOT Analysis</h2>
        <div class="grid-2">
          <div class="grid-card">
            <strong>Strengths</strong>
            ${getListItems(currentData.swot_analysis?.strengths)}
          </div>
          <div class="grid-card">
            <strong>Weaknesses</strong>
            ${getListItems(currentData.swot_analysis?.weaknesses)}
          </div>
          <div class="grid-card" style="margin-top: 10px;">
            <strong>Opportunities</strong>
            ${getListItems(currentData.swot_analysis?.opportunities)}
          </div>
          <div class="grid-card" style="margin-top: 10px;">
            <strong>Threats</strong>
            ${getListItems(currentData.swot_analysis?.threats)}
          </div>
        </div>
      </div>

      <!-- Risk Assessment -->
      <div class="section-card">
        <h2 class="section-title">Risk Assessment</h2>
        <div class="content-block">
          <div class="content-label">Market Risks</div>
          <p class="content-text">${currentData.risk_assessment?.market_risks || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Competition Risks</div>
          <p class="content-text">${currentData.risk_assessment?.competition_risks || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Operational Risks</div>
          <p class="content-text">${currentData.risk_assessment?.operational_risks || "N/A"}</p>
        </div>
        <div class="content-block">
          <div class="content-label">Legal & Compliance Risks</div>
          <p class="content-text">${currentData.risk_assessment?.legal_risks || "N/A"}</p>
        </div>
      </div>

      <!-- Scenario Planning -->
      <!-- Scenario Planning merged with Financial & Scenario Analysis -->

      <!-- Launch Roadmap -->
      <div class="section-card">
        <h2 class="section-title">Launch Roadmap</h2>
        <div class="content-block">
          <div class="content-label">Week 1-2 Milestones</div>
          ${getListItems(currentData.launch_roadmap?.week_1_2)}
        </div>
        <div class="content-block">
          <div class="content-label">Week 3-4 Milestones</div>
          ${getListItems(currentData.launch_roadmap?.week_3_4)}
        </div>
        <div class="content-block">
          <div class="content-label">Month 2 Milestones</div>
          ${getListItems(currentData.launch_roadmap?.month_2)}
        </div>
        <div class="content-block">
          <div class="content-label">Month 3 Milestones</div>
          ${getListItems(currentData.launch_roadmap?.month_3)}
        </div>
      </div>

      <!-- Founder Decision Engine -->
      <div class="section-card">
        <h2 class="section-title">Founder Decision Engine</h2>
        
        <div class="score-bar-container">
          <div class="score-bar-header">
            <span>Market Fit</span>
            <span>${currentData.founder_decision_engine?.market_fit || 50}/100</span>
          </div>
          <div class="score-bar-bg">
            <div class="score-bar-fill" style="width: ${currentData.founder_decision_engine?.market_fit || 50}%;"></div>
          </div>
        </div>

        <div class="score-bar-container">
          <div class="score-bar-header">
            <span>Competition Readiness</span>
            <span>${currentData.founder_decision_engine?.competition || 50}/100</span>
          </div>
          <div class="score-bar-bg">
            <div class="score-bar-fill" style="width: ${currentData.founder_decision_engine?.competition || 50}%;"></div>
          </div>
        </div>

        <div class="score-bar-container">
          <div class="score-bar-header">
            <span>Scalability</span>
            <span>${currentData.founder_decision_engine?.scalability || 50}/100</span>
          </div>
          <div class="score-bar-bg">
            <div class="score-bar-fill" style="width: ${currentData.founder_decision_engine?.scalability || 50}%;"></div>
          </div>
        </div>

        <div class="score-bar-container">
          <div class="score-bar-header">
            <span>Capital Efficiency</span>
            <span>${currentData.founder_decision_engine?.capital_efficiency || 50}/100</span>
          </div>
          <div class="score-bar-bg">
            <div class="score-bar-fill" style="width: ${currentData.founder_decision_engine?.capital_efficiency || 50}%;"></div>
          </div>
        </div>

        <div class="score-bar-container">
          <div class="score-bar-header">
            <span>Risk Level (Lower is Better)</span>
            <span>${currentData.founder_decision_engine?.risk || 50}/100</span>
          </div>
          <div class="score-bar-bg">
            <div class="score-bar-fill" style="width: ${currentData.founder_decision_engine?.risk || 50}%; background: #EF4444;"></div>
          </div>
        </div>
      </div>

      <!-- Final Verdict -->
      <div class="section-card verdict-card">
        <h2 class="section-title">Final Verdict</h2>
        <div class="content-block">
          <div class="content-label" style="color: rgba(255,255,255,0.7);">Strategic Evaluation</div>
          <p class="content-text" style="color: #FFFFFF; font-size: 15px; font-weight: 500; font-style: italic;">
            "${currentData.final_verdict?.context_text || "N/A"}"
          </p>
        </div>
        <div class="grid-3" style="margin-top: 20px;">
          <div>
            <div class="content-label" style="color: rgba(255,255,255,0.7);">Investment Grade</div>
            <div class="verdict-value" style="color: #34D399;">${currentData.final_verdict?.investment_grade || "B+"}</div>
          </div>
          <div>
            <div class="content-label" style="color: rgba(255,255,255,0.7);">Launch Recommendation</div>
            <div class="verdict-value" style="color: #60A5FA; font-size: 20px; padding-top: 8px;">${currentData.final_verdict?.launch_recommendation || "Pilot First"}</div>
          </div>
          <div>
            <div class="content-label" style="color: rgba(255,255,255,0.7);">Confidence Level</div>
            <div class="verdict-value" style="color: #FBBF24; font-size: 20px; padding-top: 8px;">${currentData.final_verdict?.confidence_level || "High"}</div>
          </div>
        </div>
      </div>
    </div>
  </body>
  </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const fileName = (metadata?.idea_text || "Report")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    link.download = `bizvision-ai-${fileName || 'report'}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = useCallback(() => {
    const element = document.getElementById('report-pdf-content');
    if (!element) {
      window.print();
      return;
    }

    const fileName = (metadata?.idea_text || "Report")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');

    const opt = {
      margin:       [10, 10, 10, 10], // top, left, bottom, right margins in mm
      filename:     `bizvision-ai-${fileName || 'report'}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { 
        scale: 2, 
        useCORS: true,
        logging: false,
        letterRendering: true
      },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    loadHtml2Pdf().then((html2pdfLib) => {
      html2pdfLib().set(opt).from(element).save();
    }).catch(err => {
      console.error("Failed to load html2pdf from CDN, printing natively:", err);
      window.print();
    });
  }, [metadata]);

  const handleSaveToWorkspace = useCallback(() => {
    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      setIsSaved(prev => !prev);
    }, 800);
  }, []);

  const handleTimeRangeChange = useCallback((range) => {
    setSelectedTimeRange(range);
  }, []);

  const handleGenerateBusinessPlan = useCallback(() => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      alert('AI Business Plan generation started! Check back shortly.');
    }, 2000);
  }, []);

  const defaultLabels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const defaultPoints = [45, 52, 48, 61, 59, 75, 82, 80, 88, 95, 91, 100];
  const baseLabels = trends && trends.length > 0 ? trends.map(t => t.date) : defaultLabels;
  const basePoints = trends && trends.length > 0 ? trends.map(t => {
    if (t.values && t.values.length > 0) {
      const firstVal = t.values[0];
      const val = Number(firstVal.extracted_value !== undefined ? firstVal.extracted_value : firstVal.value);
      if (!isNaN(val)) return val;
    }
    if (t.value !== undefined && t.value !== null) {
      const val = Number(t.value);
      if (!isNaN(val)) return val;
    }
    return 0;
  }) : defaultPoints;

  const dataLine = {
    labels: baseLabels,
    datasets: [
      {
        label: 'Interest velocity',
        data: basePoints,
        borderColor: '#6366F1',
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        borderWidth: 3,
        pointBackgroundColor: '#FFFFFF',
        pointBorderColor: '#6366F1',
        pointBorderWidth: 2,
        tension: 0.35,
        fill: true,
      }
    ]
  };

  const renderIdentityCircle = (type) => {
    let dotColor = 'bg-indigo-600';
    let textColor = 'text-indigo-600';
    let borderColor = 'border-indigo-200/60';
    let bgColor = 'bg-indigo-50/50';

    if (type === 'Insight') {
      dotColor = 'bg-purple-600';
      textColor = 'text-purple-600';
      borderColor = 'border-purple-200/60';
      bgColor = 'bg-purple-50/50';
    } else if (type === 'Evidence') {
      dotColor = 'bg-blue-600';
      textColor = 'text-blue-600';
      borderColor = 'border-blue-200/60';
      bgColor = 'bg-blue-50/50';
    } else if (type === 'Evidence + Insight') {
      dotColor = 'bg-indigo-600';
      textColor = 'text-indigo-600';
      borderColor = 'border-indigo-200/60';
      bgColor = 'bg-indigo-50/50';
    } else if (type === 'Financial') {
      dotColor = 'bg-emerald-600';
      textColor = 'text-emerald-600';
      borderColor = 'border-emerald-200/60';
      bgColor = 'bg-emerald-50/50';
    }

    return (
      <div className="flex items-center mb-1">
        <span className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[9px] font-extrabold uppercase tracking-widest ${bgColor} ${textColor} border ${borderColor}`}>
          <span className={`w-1.5 h-1.5 rounded-full ${dotColor} animate-pulse`}></span>
          {type}
        </span>
      </div>
    );
  };

  return (
    <div className="min-h-screen w-full bg-slate-50/50 flex flex-col relative font-sans text-slate-800">
      <ReportHeader 
        isSaved={isSaved}
        onSave={handleSaveToWorkspace}
        onDownload={handleDownloadPDF}
        isLoading={isLoading}
      />

      <main ref={reportRef} id="report-pdf-content" className="flex-1 w-full max-w-[1400px] mx-auto px-6 py-6 space-y-6 pb-24">
        <DisclaimerBanner />

        {/* Venture Statement Callout */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="p-6 md:p-8 rounded-[2rem] bg-gradient-to-r from-indigo-900 via-indigo-950 to-slate-950 text-white border border-indigo-950 shadow-lg flex flex-col md:flex-row md:items-center justify-between gap-6 relative overflow-hidden"
        >
          <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-500/10 rounded-full blur-[100px] pointer-events-none -translate-y-1/2 translate-x-1/3"></div>
          <div className="space-y-3 relative z-10">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-indigo-500/20 text-indigo-300 uppercase tracking-wider border border-indigo-500/30">
              <Icon icon="lucide:sparkles" className="animate-pulse" /> Enterprise intelligence
            </span>
            <h1 className="text-2xl md:text-3xl font-black tracking-tight text-white leading-tight">
              "{metadata?.idea_text || 'Startup Feasibility'}"
            </h1>
            <div className="flex items-center gap-4 text-xs font-bold text-slate-300">
              <span className="flex items-center gap-1"><Icon icon="lucide:map-pin" className="text-sm text-indigo-400" /> {metadata?.location || 'Global'}</span>
              <span className="flex items-center gap-1"><Icon icon="lucide:briefcase" className="text-sm text-indigo-400" /> {displayBusinessType}</span>
            </div>
          </div>
        </motion.div>

        {/* Founder Decision Engine */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.4 }}
          whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
          className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
        >
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600 shadow-sm border border-indigo-100/50">
                <Icon icon="lucide:cpu" className="text-xl" />
              </div>
              <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Founder Decision Engine</h2>
            </div>
            {renderIdentityCircle('Evidence + Insight')}
          </div>
          <div className="pt-2 space-y-6">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <CircularGauge 
                label="Market Fit" 
                value={data.founder_decision_engine?.market_fit || 50} 
                ringColor="text-indigo-600" 
                bgColor="bg-indigo-50/10 hover:border-indigo-100" 
              />
              <CircularGauge 
                label="Competition Readiness" 
                value={data.founder_decision_engine?.competition || 50} 
                ringColor="text-cyan-600" 
                bgColor="bg-cyan-50/10 hover:border-cyan-100" 
              />
              <CircularGauge 
                label="Scalability Potential" 
                value={data.founder_decision_engine?.scalability || 50} 
                ringColor="text-emerald-600" 
                bgColor="bg-emerald-50/10 hover:border-emerald-100" 
              />
              <CircularGauge 
                label="Capital Efficiency" 
                value={data.founder_decision_engine?.capital_efficiency || 50} 
                ringColor="text-violet-600" 
                bgColor="bg-violet-50/10 hover:border-violet-100" 
              />
            </div>

            <div className="p-4 bg-red-50/35 border border-red-100/50 rounded-2xl flex flex-col md:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-red-100/80 flex items-center justify-center text-red-600 shadow-sm">
                  <Icon icon="lucide:alert-triangle" className="text-xl" />
                </div>
                <div className="text-left">
                  <h4 className="text-sm font-bold text-slate-900">Risk Factor Assessment</h4>
                  <p className="text-xs text-slate-500 font-semibold leading-normal">Lower risk scores indicate higher probability of success and smoother launch execution.</p>
                </div>
              </div>
              <div className="flex items-center gap-2 self-start md:self-center">
                <span className="text-xs font-bold uppercase text-slate-400">Risk Score:</span>
                <span className="px-3.5 py-1.5 rounded-full bg-red-100 text-red-700 font-extrabold text-sm flex items-center gap-1.5 shadow-sm border border-red-200/30">
                  {data.founder_decision_engine?.risk || 50}/100
                </span>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Executive Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.4 }}
          whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
          className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
        >
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-purple-50 text-purple-600 shadow-sm border border-purple-100/50">
                <Icon icon="lucide:file-text" className="text-xl" />
              </div>
              <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Executive Summary</h2>
            </div>
            {renderIdentityCircle('Insight')}
          </div>
          <div className="pt-2 space-y-4">
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Corporate Title</span>
              <h3 className="text-lg font-extrabold text-indigo-900">"{data.executive_summary?.title}"</h3>
            </div>
            <div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Business Summary</span>
              <p className="text-sm leading-relaxed text-slate-600 font-medium">{data.executive_summary?.business_summary}</p>
            </div>
            <div className="p-4 rounded-xl bg-indigo-50/40 border border-indigo-100/50 shadow-sm">
              <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">One Paragraph Verdict</span>
              <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.executive_summary?.one_paragraph_verdict}</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              <div className="p-4 bg-emerald-50/20 border border-emerald-100 rounded-xl shadow-sm">
                <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider block mb-1">Key Opportunity</span>
                <p className="text-xs text-slate-600 leading-relaxed font-medium">{data.executive_summary?.key_opportunity}</p>
              </div>
              <div className="p-4 bg-red-50/20 border border-red-100 rounded-xl shadow-sm">
                <span className="text-[10px] font-bold text-red-600 uppercase tracking-wider block mb-1">Biggest Challenge</span>
                <p className="text-xs text-slate-600 leading-relaxed font-medium">{data.executive_summary?.biggest_challenge}</p>
              </div>
            </div>
          </div>
        </motion.div>

        {/* 2-Column Dashboard Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
          {/* Left Column Stack */}
          <div className="space-y-6 flex flex-col">
            {/* Market Overview */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600 shadow-sm border border-indigo-100/50">
                    <Icon icon="lucide:bar-chart-2" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Market Overview</h2>
                </div>
                {renderIdentityCircle('Evidence + Insight')}
              </div>
              <div className="pt-2 space-y-4">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Search Demand Velocity</span>
                  <p className="text-sm leading-relaxed text-slate-600 font-medium">{data.market_overview?.search_demand}</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Trend Direction</span>
                    <p className="text-xs text-slate-700 leading-relaxed font-bold">{data.market_overview?.trend_direction}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Market Maturity Stage</span>
                    <p className="text-xs text-slate-700 leading-relaxed font-bold">{data.market_overview?.market_maturity}</p>
                  </div>
                </div>
                <div className="bg-white rounded-xl p-4 border border-slate-100 shadow-sm mt-4">
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-3">Local Search Velocity (Past 12 Months)</span>
                  <div className="h-64 w-full relative">
                    <Line data={dataLine} options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }} />
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Competitor Intelligence */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-blue-50 text-blue-600 shadow-sm border border-blue-100/50">
                    <Icon icon="lucide:users" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Competitor Intelligence</h2>
                </div>
                {renderIdentityCircle('Evidence')}
              </div>
              <div className="pt-2 space-y-4">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Market Gaps & Vulnerabilities</span>
                  <p className="text-sm leading-relaxed text-slate-600 font-medium">{data.competitor_intelligence?.market_gaps}</p>
                </div>
                
                {competitors.length > 0 && (
                  <div className="grid grid-cols-1 gap-6 pt-2">
                    <div className="space-y-3">
                      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Local Rivals Map (From Live API Sourcing)</span>
                      {competitors.slice(0, 4).map((comp, idx) => (
                        <motion.div
                          key={idx}
                          whileHover={{ x: 4 }}
                          className="p-4 bg-slate-50/50 hover:bg-slate-50/80 rounded-xl border border-slate-100 hover:border-blue-200 flex items-start gap-4 transition-all"
                        >
                          <div className="w-10 h-10 bg-blue-50 text-blue-600 font-extrabold flex items-center justify-center rounded-lg flex-shrink-0 text-sm">
                            {(comp.name || comp.title || 'CO').slice(0, 2).toUpperCase()}
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center justify-between">
                              <span className="text-sm font-bold text-slate-800">{comp.name || comp.title}</span>
                              <span className="text-xs font-bold text-amber-500">★ {comp.rating || "4.0"} ({comp.reviews || "0"} reviews)</span>
                            </div>
                            <p className="text-xs text-slate-400 mt-1 font-semibold">{comp.address}</p>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                    <div className="bg-slate-50/30 rounded-2xl p-6 border border-slate-100 shadow-sm">
                      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-4">Competitor Ratings Benchmarking</span>
                      <CompetitorsRatingsChart competitors={competitors} />
                    </div>
                  </div>
                )}
              </div>
            </motion.div>

            {/* Opportunity Analysis */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-purple-50 text-purple-600 shadow-sm border border-purple-100/50">
                    <Icon icon="lucide:lightbulb" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Opportunity Analysis</h2>
                </div>
                {renderIdentityCircle('Insight')}
              </div>
              <div className="pt-2 space-y-4">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Why This Business May Work</span>
                  <p className="text-sm leading-relaxed text-slate-600 font-medium">{data.opportunity_analysis?.why_work}</p>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Untapped Local Opportunities</span>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2">
                    {(data.opportunity_analysis?.untapped_opportunities || []).map((opp, i) => (
                      <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-semibold bg-slate-50 p-2 rounded-lg border border-slate-100 shadow-sm">
                        <span className="text-indigo-500 font-bold">•</span> {opp}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Premium Positioning Hook</span>
                  <p className="text-xs text-slate-600 leading-relaxed font-semibold bg-slate-50/50 p-3 rounded-xl border border-slate-100 shadow-sm">{data.opportunity_analysis?.premium_positioning}</p>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Right Column Stack */}
          <div className="space-y-6 flex flex-col">
            {/* Financial & Scenario Analysis */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-emerald-50 text-emerald-600 shadow-sm border border-emerald-100/50">
                    <Icon icon="lucide:calculator" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Financial & Scenario Analysis</h2>
                </div>
                {renderIdentityCircle('Financial')}
              </div>
              <div className="pt-2 space-y-6">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">Cost & Capital Analysis</span>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 text-center shadow-sm">
                      <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block mb-1">Minimum Startup</span>
                      <span className="text-base font-extrabold text-slate-700">{formatCurrencyToINR(data.cost_capital_analysis?.estimated_startup_cost)}</span>
                    </div>
                    <div className="p-4 bg-indigo-50/50 rounded-xl border border-indigo-100 text-center shadow-sm">
                      <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Monthly Operating</span>
                      <span className="text-base font-extrabold text-slate-700">{formatCurrencyToINR(data.cost_capital_analysis?.operating_cost)}</span>
                    </div>
                    <div className="p-4 bg-cyan-50/50 rounded-xl border border-cyan-100 text-center shadow-sm">
                      <span className="text-[10px] font-bold text-cyan-600 uppercase tracking-wider block mb-1">Recommended Capital</span>
                      <span className="text-base font-extrabold text-cyan-700">{formatCurrencyToINR(data.cost_capital_analysis?.recommended_capital)}</span>
                    </div>
                  </div>
                </div>

                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">Scenario Planning</span>
                  <div className="grid grid-cols-3 gap-4">
                    <div className="p-4 bg-emerald-50/20 border border-emerald-100 rounded-xl text-center shadow-sm">
                      <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider block mb-1">Best Case</span>
                      <p className="text-xs text-slate-700 font-bold mt-2">{formatCurrencyToINR(data.scenario_planning?.best_case)}</p>
                    </div>
                    <div className="p-4 bg-indigo-50/20 border border-indigo-100 rounded-xl text-center shadow-sm">
                      <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-1">Expected Case</span>
                      <p className="text-xs text-slate-700 font-bold mt-2">{formatCurrencyToINR(data.scenario_planning?.expected_case)}</p>
                    </div>
                    <div className="p-4 bg-red-50/20 border border-red-100 rounded-xl text-center shadow-sm">
                      <span className="text-[10px] font-bold text-red-600 uppercase tracking-wider block mb-1">Worst Case</span>
                      <p className="text-xs text-slate-700 font-bold mt-2">{formatCurrencyToINR(data.scenario_planning?.worst_case)}</p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Revenue Model */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-emerald-50 text-emerald-600 shadow-sm border border-emerald-100/50">
                    <Icon icon="lucide:wallet" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Revenue Model</h2>
                </div>
                {renderIdentityCircle('Financial')}
              </div>
              <div className="pt-2 space-y-4">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Primary Revenue Streams</span>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2">
                    {(data.revenue_model?.revenue_streams || []).map((stream, i) => (
                      <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-semibold bg-slate-50 p-2 rounded-lg border border-slate-100 shadow-sm">
                        <span className="text-emerald-500 font-bold">•</span> {stream}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Upsell Mechanics</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.revenue_model?.upsells}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Memberships Offering</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.revenue_model?.memberships}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Subscription Tiers</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.revenue_model?.subscriptions}</p>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Customer Intelligence */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-purple-50 text-purple-600 shadow-sm border border-purple-100/50">
                    <Icon icon="lucide:user-check" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Customer Intelligence</h2>
                </div>
                {renderIdentityCircle('Insight')}
              </div>
              <div className="pt-2 space-y-4">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Target Customer Persona</span>
                  <p className="text-sm leading-relaxed text-slate-600 font-medium">{data.customer_intelligence?.customer_persona}</p>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Observed Pain Points</span>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2">
                    {(data.customer_intelligence?.pain_points || []).map((pt, i) => (
                      <li key={i} className="text-xs text-slate-600 leading-normal flex gap-1.5 font-semibold bg-slate-50 p-2 rounded-lg border border-slate-100 shadow-sm">
                        <span className="text-indigo-500 font-bold">•</span> {pt}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                  <div>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Buying Behavior Drivers</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold bg-slate-50/50 p-3 rounded-xl border border-slate-100 shadow-sm">{data.customer_intelligence?.buying_behavior}</p>
                  </div>
                  <div>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Spending Patterns & Wallet Share</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold bg-slate-50/50 p-3 rounded-xl border border-slate-100 shadow-sm">{data.customer_intelligence?.spending_patterns}</p>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Industry Trends */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-blue-50 text-blue-600 shadow-sm border border-blue-100/50">
                    <Icon icon="lucide:globe" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Industry Trends</h2>
                </div>
                {renderIdentityCircle('Evidence')}
              </div>
              <div className="pt-2 space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">News Sentiment</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-medium">{data.industry_trends?.news_analysis}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Macro Trend Analysis</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-medium">{data.industry_trends?.trend_analysis}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Emerging Standards</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-medium">{data.industry_trends?.emerging_changes}</p>
                  </div>
                </div>

                {/* Live News Signals */}
                {news.length > 0 && (
                  <div className="pt-2">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-3">Live Industry News Signals</span>
                    <div className="grid grid-cols-1 gap-4">
                      {news.slice(0, 3).map((item, idx) => (
                        <motion.a
                          key={idx}
                          href={item.link}
                          target="_blank"
                          rel="noopener noreferrer"
                          whileHover={{ x: 4 }}
                          className="block p-4 bg-slate-50/50 hover:bg-slate-50 rounded-xl border border-slate-100 hover:border-blue-200 transition-all shadow-sm"
                        >
                          <span className="text-[10px] font-bold text-indigo-600 block mb-1">{item.source || "News Source"}</span>
                          <p className="text-xs font-bold text-slate-800 line-clamp-2 leading-relaxed">{item.title}</p>
                          {item.date && <span className="text-[9px] text-slate-400 block mt-2 font-bold">{item.date}</span>}
                        </motion.a>
                      ))}
                    </div>
                  </div>
                )}

                {/* Live Shopping Benchmarks */}
                {shopping.length > 0 && (
                  <div className="pt-2">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-3">Alternative Product & Pricing Benchmarks</span>
                    <div className="grid grid-cols-2 gap-4">
                      {shopping.slice(0, 4).map((item, idx) => (
                        <motion.div
                          key={idx}
                          whileHover={{ y: -3 }}
                          className="p-3 bg-slate-50/50 hover:bg-white rounded-xl border border-slate-100 hover:border-blue-100 flex flex-col justify-between shadow-sm transition-all"
                        >
                          <p className="text-[11px] font-bold text-slate-800 line-clamp-2 leading-relaxed">{item.title}</p>
                          <div className="flex justify-between items-center mt-3 pt-2 border-t border-slate-100">
                            <span className="text-xs font-extrabold text-emerald-600">{item.price || "N/A"}</span>
                            {item.source && <span className="text-[9px] text-slate-400 font-bold truncate max-w-[50px]">{item.source}</span>}
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </motion.div>

            {/* Risk Assessment */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              transition={{ duration: 0.4 }}
              whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
              className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600 shadow-sm border border-indigo-100/50">
                    <Icon icon="lucide:shield-alert" className="text-xl" />
                  </div>
                  <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Risk Assessment</h2>
                </div>
                {renderIdentityCircle('Evidence + Insight')}
              </div>
              <div className="pt-2 space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Market Risks</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.risk_assessment?.market_risks}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Competition Risks</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.risk_assessment?.competition_risks}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Operational Risks</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.risk_assessment?.operational_risks}</p>
                  </div>
                  <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm">
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Legal & Compliance Risks</span>
                    <p className="text-xs text-slate-600 leading-relaxed font-semibold">{data.risk_assessment?.legal_risks}</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>

        {/* SWOT Analysis */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.4 }}
          whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
          className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
        >
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600 shadow-sm border border-indigo-100/50">
                <Icon icon="lucide:layers" className="text-xl" />
              </div>
              <h2 className="text-xl font-extrabold tracking-tight text-slate-900">SWOT Analysis</h2>
            </div>
            {renderIdentityCircle('Evidence + Insight')}
          </div>
          <div className="pt-2">
            <SWOTAnalysisSection swot={data.swot_analysis} />
          </div>
        </motion.div>

        {/* Launch Roadmap */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.4 }}
          whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
          className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
        >
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600 shadow-sm border border-indigo-100/50">
                <Icon icon="lucide:map" className="text-xl" />
              </div>
              <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Launch Roadmap</h2>
            </div>
            {renderIdentityCircle('Evidence + Insight')}
          </div>
          <div className="pt-2 grid grid-cols-1 md:grid-cols-4 gap-4">
            {[
              { title: "Weeks 1-2", tasks: data.launch_roadmap?.week_1_2 },
              { title: "Weeks 3-4", tasks: data.launch_roadmap?.week_3_4 },
              { title: "Month 2", tasks: data.launch_roadmap?.month_2 },
              { title: "Month 3", tasks: data.launch_roadmap?.month_3 }
            ].map((step, sIdx) => (
              <motion.div
                key={sIdx}
                whileHover={{ y: -3 }}
                className="p-4 bg-slate-50 border border-slate-100 rounded-xl shadow-sm transition-all"
              >
                <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-wider block mb-2 font-extrabold">{step.title}</span>
                <ul className="space-y-1.5">
                  {(step.tasks || []).map((task, idx) => (
                    <li key={idx} className="text-xs text-slate-600 font-semibold leading-normal flex gap-1"><span className="text-indigo-500 font-bold">•</span> {task}</li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Final Verdict */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.4 }}
          whileHover={{ y: -4, borderColor: 'rgba(99,102,241,0.2)', boxShadow: '0 20px 40px rgba(99,102,241,0.04)' }}
          className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-200/60 shadow-[0_8px_30px_rgb(0,0,0,0.015)] space-y-6 transition-colors duration-300"
        >
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-indigo-50 text-indigo-600 shadow-sm border border-indigo-100/50">
                <Icon icon="lucide:award" className="text-xl" />
              </div>
              <h2 className="text-xl font-extrabold tracking-tight text-slate-900">Final Verdict</h2>
            </div>
            {renderIdentityCircle('Evidence + Insight')}
          </div>
          <div className="pt-2">
            <FinalVerdict 
              scores={{ viability: data.founder_decision_engine?.market_fit }}
              analysis={{ final_recommendation: JSON.stringify({ next_step: data.final_verdict?.context_text, status: data.final_verdict?.launch_recommendation, grade: data.final_verdict?.investment_grade, confidence: data.final_verdict?.confidence_level }) }}
              onGenerate={handleGenerateBusinessPlan}
              onSave={handleSaveToWorkspace}
              isLoading={isGenerating}
              metadata={metadata}
            />
          </div>
        </motion.div>
      </main>
    </div>
  );
};

// ─── FINAL VERDICT PANEL ───────────────────────────────────────────────────
const FinalVerdict = ({ scores, analysis, onGenerate, onSave, isLoading, metadata }) => {
  const viability = scores?.viability || 50;
  const statusColor = viability >= 75 ? "from-emerald-600 to-emerald-700" : 
                      viability >= 45 ? "from-amber-600 to-amber-700" : 
                      "from-red-600 to-red-700";
  
  const parsed = parseJSON(analysis?.final_recommendation, {});
  const nextStep = parsed.next_step || "Validate economic parameters before launch.";
  const statusBadge = parsed.status || "Approved for Pilot";

  return (
    <div className={`bg-gradient-to-r ${statusColor} rounded-[2rem] p-8 md:p-12 shadow-2xl relative overflow-hidden flex flex-col gap-8 text-white`}>
      <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full blur-[100px] pointer-events-none -translate-y-1/2 translate-x-1/3"></div>
      <div className="relative z-10">
        <p className="text-xs font-bold uppercase tracking-widest text-white/80 mb-6">Investment Verdict Summary</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">VC Confidence</p>
            <AnimatedViabilityValue value={viability} />
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Status Verdict</p>
            <p className="text-lg font-bold">{statusBadge}</p>
          </div>
        </div>
        <div className="pt-6 border-t border-white/20">
          <p className="text-xs font-bold uppercase tracking-wider text-white/70 mb-2">Recommended Next Action Step</p>
          <p className="text-sm font-semibold text-white leading-relaxed">"{nextStep}"</p>
        </div>
      </div>

    </div>
  );
};

const parseJSON = (raw, defaultValue) => {
  if (!raw) return defaultValue;
  try {
    let clean = raw.trim();
    if (clean.startsWith("```")) {
      clean = clean.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
    }
    return JSON.parse(clean);
  } catch (e) {
    return defaultValue;
  }
};

export default IntelligenceReport;
